using System.Threading.Tasks;
using Terminus.Generator.Tests.Unit;
using Xunit;

namespace Terminus.Generator.Tests.Unit;

public class CancellationTokenDefaultValueTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_Method_With_Optional_ValueType_Default_Should_Generate_Correct_Default_Value()
    {
        const string source = """
            using System;
            using System.Threading;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo;

            public class MyOperationAttribute : Attribute;

            [FacadeOf<MyOperationAttribute>]
            public partial interface IMyOperation;

            public class MyHandler
            {
                [MyOperation]
                public Task DoSomethingAsync(CancellationToken ct = default) => Task.CompletedTask;
            }
            """;
        
        var expectedCode =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.MyHandler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IMyOperation
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.MyHandler.DoSomethingAsync(System.Threading.CancellationToken)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task DoSomethingAsync(global::System.Threading.CancellationToken ct = default);
                }
 
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IMyOperation))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.MyHandler"/>
                /// </summary>
                public sealed class IMyOperation_Generated : global::Demo.IMyOperation
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IMyOperation_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IMyOperation_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }
 
                    async global::System.Threading.Tasks.Task global::Demo.IMyOperation.DoSomethingAsync(global::System.Threading.CancellationToken ct = default)
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.MyHandler>(_serviceProvider).DoSomethingAsync(ct).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IMyOperation_Generated.g.cs", expectedCode));
    }
}
