namespace Terminus.Generator.Tests.Unit;

/// <summary>
/// Tests for generic FacadeOf&lt;T&gt; attribute with strongly-typed interceptors.
/// </summary>
public class GenericFacadeOfTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_GenericFacadeOf_Should_Generate_With_StronglyTyped_Context()
    {
        const string source = """
            using System;
            using Terminus;

            namespace Demo;

            // Custom attribute with metadata
            public class HttpHandlerAttribute : Attribute
            {
                public string Route { get; }
                public HttpHandlerAttribute(string route) => Route = route;
            }

            // Generic facade using single attribute type
            [FacadeOf<HttpHandlerAttribute>]
            public partial interface IHttpHandlers;

            // Handler with attribute
            public class UserHandlers
            {
                [HttpHandler("/users/{id}")]
                public string GetUser(string id) => $"User {id}";
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHttpHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.GetUser(string)"/>
                    /// </summary>
                    string GetUser(string id);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHttpHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                public sealed class IHttpHandlers_Generated : global::Demo.IHttpHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHttpHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHttpHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    string global::Demo.IHttpHandlers.GetUser(string id)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).GetUser(id);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHttpHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_GenericFacadeOf_With_Interceptors_Should_Generate_StronglyTyped_Context()
    {
        const string source = """
            using System;
            using Terminus;

            namespace Demo;

            // Custom attribute with metadata
            public class HttpHandlerAttribute : Attribute
            {
                public string Route { get; }
                public HttpHandlerAttribute(string route) => Route = route;
            }

            // Strongly-typed interceptor
            public class RoutingInterceptor : FacadeInterceptor<HttpHandlerAttribute>
            {
                public override TResult Intercept<TResult>(
                    FacadeInvocationContext<HttpHandlerAttribute> context,
                    FacadeInvocationDelegate<TResult> next)
                {
                    // Can access Route property without casting!
                    var route = context.MethodAttribute.Route;
                    Console.WriteLine($"Handling {route}");
                    return next();
                }
            }

            // Generic facade with interceptor
            [FacadeOf<HttpHandlerAttribute>(Interceptors = new[] { typeof(RoutingInterceptor) })]
            public partial interface IHttpHandlers;

            // Handler with attribute
            public class UserHandlers
            {
                [HttpHandler("/users/{id}")]
                public string GetUser(string id) => $"User {id}";
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHttpHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.GetUser(string)"/>
                    /// </summary>
                    string GetUser(string id);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHttpHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                public sealed class IHttpHandlers_Generated : global::Demo.IHttpHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    private readonly object[] _interceptors;
                    /// <summary>
                    /// Initializes a new instance of the IHttpHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHttpHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                        _interceptors = new object[]
                        {
                            global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.RoutingInterceptor>(serviceProvider)
                        };
                    }

                    string global::Demo.IHttpHandlers.GetUser(string id)
                    {
                        var handlers = new global::Terminus.FacadeSyncHandlerDescriptor<string>[]
                        {
                            new global::Terminus.FacadeSyncHandlerDescriptor<string>(typeof(global::Demo.UserHandlers), new global::Demo.HttpHandlerAttribute("/users/{id}"), isStatic: false, () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).GetUser(id))
                        };
                        var context = new global::Terminus.FacadeInvocationContext<global::Demo.HttpHandlerAttribute>(_serviceProvider, typeof(global::Demo.IHttpHandlers).GetMethod("GetUser")!, new object? [] { id }, typeof(global::Demo.UserHandlers), new global::Demo.HttpHandlerAttribute("/users/{id}"), new global::System.Collections.Generic.Dictionary<string, object?>(), global::Terminus.ReturnTypeKind.Result, handlers, isAggregated: false);
                        return ExecuteWithInterceptors<string>(context, handlers => ((global::Terminus.FacadeSyncHandlerDescriptor<string>)(handlers ?? context.Handlers)[0]).Invoke());
                    }

                    private TResult ExecuteWithInterceptors<TResult>(global::Terminus.FacadeInvocationContext<global::Demo.HttpHandlerAttribute> context, global::Terminus.FacadeInvocationDelegate<TResult> target)
                    {
                        var index = 0;
                        global::Terminus.FacadeInvocationDelegate<TResult> BuildPipeline()
                        {
                            if (index >= _interceptors.Length)
                                return target;
                            var currentIndex = index++;
                            var next = BuildPipeline();
                            if (_interceptors[currentIndex] is global::Terminus.ISyncFacadeInterceptor<global::Demo.HttpHandlerAttribute> sync)
                                return handlers => sync.Intercept(context, nextHandlers => next(nextHandlers ?? handlers));
                            return next;
                        }

                        return BuildPipeline()(null);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHttpHandlers_Generated.g.cs", expected));
    }
}
