namespace Terminus.Generator.Tests.Unit;

/// <summary>
/// Tests for open generic types with facade method attributes.
/// </summary>
public class OpenGenericTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_OpenGenericInterface_With_ClassLevelAttribute_Should_Generate_For_ClosedImplementations()
    {
        const string source = """
            using System;
            using Terminus;

            namespace Demo;

            public class HandlerAttribute : Attribute { }

            [FacadeOf(typeof(HandlerAttribute))]
            public partial interface IHandlers;

            // Open generic interface with class-level attribute
            [Handler]
            public interface IHandler<T>
            {
                void Handle(T value);
            }

            // Closed implementations
            public class StringHandler : IHandler<string>
            {
                public void Handle(string value) => Console.WriteLine($"String: {value}");
            }

            public class IntHandler : IHandler<int>
            {
                public void Handle(int value) => Console.WriteLine($"Int: {value}");
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.IHandler<int>"/><br/>
                /// <see cref="Demo.IHandler<string>"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.IHandler<string>.Handle(string)"/>
                    /// </summary>
                    void Handle(string value);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.IHandler<int>.Handle(int)"/>
                    /// </summary>
                    void Handle(int value);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.IHandler<int>"/><br/>
                /// <see cref="Demo.IHandler<string>"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.Handle(string value)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Demo.IHandler<string>>(_serviceProvider))
                        {
                            handler.Handle(value);
                        }
                    }

                    void global::Demo.IHandlers.Handle(int value)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Demo.IHandler<int>>(_serviceProvider))
                        {
                            handler.Handle(value);
                        }
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_OpenGenericClass_With_FieldUsage_Should_Generate_For_ClosedTypes()
    {
        const string source = """
            using System;
            using Terminus;

            namespace Demo;

            public class HandlerAttribute : Attribute { }

            [FacadeOf(typeof(HandlerAttribute))]
            public partial interface IHandlers;

            // Open generic class with class-level attribute
            [Handler]
            public class GenericHandler<T>
            {
                public void Process(T value) => Console.WriteLine($"Processing: {value}");
            }

            // Usage via fields
            public class ServiceA
            {
                private readonly GenericHandler<string> _handler;
            }

            public class ServiceB
            {
                private readonly GenericHandler<int> _handler;
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.GenericHandler<int>"/><br/>
                /// <see cref="Demo.GenericHandler<string>"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.GenericHandler<string>.Process(string)"/>
                    /// </summary>
                    void Process(string value);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.GenericHandler<int>.Process(int)"/>
                    /// </summary>
                    void Process(int value);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.GenericHandler<int>"/><br/>
                /// <see cref="Demo.GenericHandler<string>"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.Process(string value)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.GenericHandler<string>>(_serviceProvider).Process(value);
                    }

                    void global::Demo.IHandlers.Process(int value)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.GenericHandler<int>>(_serviceProvider).Process(value);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_OpenGenericInterface_With_MethodLevelAttribute_Should_Generate_Only_Attributed_Methods()
    {
        const string source = """
            using System;
            using Terminus;

            namespace Demo;

            public class HandlerAttribute : Attribute { }

            [FacadeOf(typeof(HandlerAttribute))]
            public partial interface IHandlers;

            // Open generic interface with method-level attribute
            public interface IHandler<T>
            {
                [Handler]
                void Handle(T value);

                void OtherMethod(T value);  // Not included (no attribute)
            }

            // Closed implementations
            public class StringHandler : IHandler<string>
            {
                public void Handle(string value) => Console.WriteLine($"String: {value}");
                public void OtherMethod(string value) { }
            }

            public class IntHandler : IHandler<int>
            {
                public void Handle(int value) => Console.WriteLine($"Int: {value}");
                public void OtherMethod(int value) { }
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.IHandler<int>"/><br/>
                /// <see cref="Demo.IHandler<string>"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.IHandler<string>.Handle(string)"/>
                    /// </summary>
                    void Handle(string value);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.IHandler<int>.Handle(int)"/>
                    /// </summary>
                    void Handle(int value);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.IHandler<int>"/><br/>
                /// <see cref="Demo.IHandler<string>"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.Handle(string value)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Demo.IHandler<string>>(_serviceProvider))
                        {
                            handler.Handle(value);
                        }
                    }

                    void global::Demo.IHandlers.Handle(int value)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Demo.IHandler<int>>(_serviceProvider))
                        {
                            handler.Handle(value);
                        }
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_OpenGeneric_With_MultipleTypeParameters_Should_Generate_For_All_ClosedTypes()
    {
        const string source = """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo;

            public class HandlerAttribute : Attribute { }

            [FacadeOf(typeof(HandlerAttribute))]
            public partial interface IHandlers;

            [Handler]
            public interface IHandler<TRequest, TResponse>
            {
                Task<TResponse> HandleAsync(TRequest request);
            }

            public class StringIntHandler : IHandler<string, int>
            {
                public Task<int> HandleAsync(string request) => Task.FromResult(request.Length);
            }

            public class IntStringHandler : IHandler<int, string>
            {
                public Task<string> HandleAsync(int request) => Task.FromResult(request.ToString());
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.IHandler<int, string>"/><br/>
                /// <see cref="Demo.IHandler<string, int>"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.IHandler<string, int>.HandleAsync(string)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task<int> HandleAsync(string request);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.IHandler<int, string>.HandleAsync(int)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task<string> HandleAsync(int request);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.IHandler<int, string>"/><br/>
                /// <see cref="Demo.IHandler<string, int>"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Threading.Tasks.Task<int> global::Demo.IHandlers.HandleAsync(string request)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.IHandler<string, int>>(_serviceProvider).HandleAsync(request).ConfigureAwait(false);
                    }

                    async global::System.Threading.Tasks.Task<string> global::Demo.IHandlers.HandleAsync(int request)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.IHandler<int, string>>(_serviceProvider).HandleAsync(request).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_OpenGeneric_With_Aggregation_Should_Combine_ClosedGeneric_Methods()
    {
        const string source = """
            using System;
            using Terminus;

            namespace Demo;

            public class NotificationAttribute : Attribute { }

            [FacadeOf(typeof(NotificationAttribute), AggregationMode = FacadeAggregationMode.Commands)]
            public partial interface INotifications;

            [Notification]
            public interface INotificationHandler<T>
            {
                void Handle(T notification);
            }

            // Multiple handlers for string notification
            public class EmailHandler : INotificationHandler<string>
            {
                public void Handle(string notification) => Console.WriteLine($"Email: {notification}");
            }

            public class LogHandler : INotificationHandler<string>
            {
                public void Handle(string notification) => Console.WriteLine($"Log: {notification}");
            }

            // Single handler for int notification
            public class IntHandler : INotificationHandler<int>
            {
                public void Handle(int notification) => Console.WriteLine($"Int: {notification}");
            }
            """;

        const string expected = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.INotificationHandler<int>"/><br/>
                /// <see cref="Demo.INotificationHandler<string>"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface INotifications
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.INotificationHandler<string>.Handle(string)"/>
                    /// </summary>
                    void Handle(string notification);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.INotificationHandler<int>.Handle(int)"/>
                    /// </summary>
                    void Handle(int notification);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.INotifications))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.INotificationHandler<int>"/><br/>
                /// <see cref="Demo.INotificationHandler<string>"/><br/>
                /// </summary>
                public sealed class INotifications_Generated : global::Demo.INotifications
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the INotifications_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public INotifications_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.INotifications.Handle(string notification)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Demo.INotificationHandler<string>>(_serviceProvider))
                        {
                            handler.Handle(notification);
                        }
                    }

                    void global::Demo.INotifications.Handle(int notification)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::Demo.INotificationHandler<int>>(_serviceProvider))
                        {
                            handler.Handle(notification);
                        }
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_INotifications_Generated.g.cs", expected));
    }
}
