// <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [ScopedEntryPointFacade]
                public partial interface IFacade;
                
                public static class TestEntryPoints
                {
                    [EntryPoint]
                    public static void Hello(string world, CancellationToken cancellationToken) 
                    { 
                        Console.WriteLine($"hello {world}"); 
                    }
                }
            }
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, System.Threading.CancellationToken cancellationToken);
                    void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IFacade> _dispatcher;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }
            
                    public void Hello(string world, System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        Demo.TestEntryPoints.Hello(world, cancellationToken);
                    }
            
                    public void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _dispatcher.Publish(context, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointFacadeFor_Demo_IFacade(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<ScopedDispatcher<Demo.IFacade>>();
                        services.AddTransient<IEntryPointRouter<Demo.IFacade>, DefaultEntryPointRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string), typeof(System.Threading.CancellationToken) })!, (context, ct) => Demo.TestEntryPoints.Hello(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context), ct)));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }