namespace Terminus.Generator.Tests.Unit.Generator;

/// <summary>
/// Tests for method aggregation behavior.
/// When multiple methods have the same signature, they should all execute in sequence within a single facade method.
/// This is similar to MediatR's notification pattern where multiple handlers execute for the same notification.
/// </summary>
public class AggregationTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_Multiple_Void_Handlers_With_Same_Signature_Should_Execute_All_In_Sequence()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface INotificationBus;

                public class HandlerAttribute : Attribute;

                // Multiple handlers for the same notification type - all should execute
                public class EmailNotificationHandler
                {
                    [Handler]
                    public void Handle(UserCreatedNotification notification)
                    {
                        Console.WriteLine($"Sending email to: {notification.Email}");
                    }
                }

                public class LoggingNotificationHandler
                {
                    [Handler]
                    public void Handle(UserCreatedNotification notification)
                    {
                        Console.WriteLine($"Logging user creation: {notification.UserId}");
                    }
                }

                public class AuditNotificationHandler
                {
                    [Handler]
                    public void Handle(UserCreatedNotification notification)
                    {
                        Console.WriteLine($"Auditing user creation: {notification.UserId}");
                    }
                }

                public record UserCreatedNotification(int UserId, string Email);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.AuditNotificationHandler"/><br/>
                /// <see cref="Demo.EmailNotificationHandler"/><br/>
                /// <see cref="Demo.LoggingNotificationHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface INotificationBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.EmailNotificationHandler.Handle(Demo.UserCreatedNotification)"/><br/>
                    /// <see cref="Demo.LoggingNotificationHandler.Handle(Demo.UserCreatedNotification)"/><br/>
                    /// <see cref="Demo.AuditNotificationHandler.Handle(Demo.UserCreatedNotification)"/>
                    /// </summary>
                    void Handle(global::Demo.UserCreatedNotification notification);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.INotificationBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.AuditNotificationHandler"/><br/>
                /// <see cref="Demo.EmailNotificationHandler"/><br/>
                /// <see cref="Demo.LoggingNotificationHandler"/><br/>
                /// </summary>
                public sealed class INotificationBus_Generated : global::Demo.INotificationBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the INotificationBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public INotificationBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.INotificationBus.Handle(global::Demo.UserCreatedNotification notification)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.EmailNotificationHandler>(_serviceProvider).Handle(notification);
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.LoggingNotificationHandler>(_serviceProvider).Handle(notification);
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.AuditNotificationHandler>(_serviceProvider).Handle(notification);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_INotificationBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_Multiple_Result_Handlers_With_Same_Signature_Should_Yield_All_Results()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface IQueryBus;

                public class HandlerAttribute : Attribute;

                // Multiple handlers that all contribute results
                public class PrimarySearchHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(1, "Primary Result");
                    }
                }

                public class SecondarySearchHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(2, "Secondary Result");
                    }
                }

                public class TertiarySearchHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(3, "Tertiary Result");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.PrimarySearchHandler"/><br/>
                /// <see cref="Demo.SecondarySearchHandler"/><br/>
                /// <see cref="Demo.TertiarySearchHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.PrimarySearchHandler.Search(string)"/><br/>
                    /// <see cref="Demo.SecondarySearchHandler.Search(string)"/><br/>
                    /// <see cref="Demo.TertiarySearchHandler.Search(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<global::Demo.User> Search(string query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.PrimarySearchHandler"/><br/>
                /// <see cref="Demo.SecondarySearchHandler"/><br/>
                /// <see cref="Demo.TertiarySearchHandler"/><br/>
                /// </summary>
                public sealed class IQueryBus_Generated : global::Demo.IQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<global::Demo.User> global::Demo.IQueryBus.Search(string query)
                    {
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.PrimarySearchHandler>(_serviceProvider).Search(query);
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.SecondarySearchHandler>(_serviceProvider).Search(query);
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TertiarySearchHandler>(_serviceProvider).Search(query);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IQueryBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_Multiple_Async_Result_Handlers_Should_Yield_All_Results()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface IAsyncQueryBus;

                public class HandlerAttribute : Attribute;

                public class DatabaseSearchHandler
                {
                    [Handler]
                    public async Task<User> SearchAsync(string query)
                    {
                        await Task.Delay(10);
                        return new User(1, "DB Result");
                    }
                }

                public class CacheSearchHandler
                {
                    [Handler]
                    public async Task<User> SearchAsync(string query)
                    {
                        await Task.Delay(5);
                        return new User(2, "Cache Result");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.CacheSearchHandler"/><br/>
                /// <see cref="Demo.DatabaseSearchHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IAsyncQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.DatabaseSearchHandler.SearchAsync(string)"/><br/>
                    /// <see cref="Demo.CacheSearchHandler.SearchAsync(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IAsyncEnumerable<global::Demo.User> SearchAsync(string query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IAsyncQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.CacheSearchHandler"/><br/>
                /// <see cref="Demo.DatabaseSearchHandler"/><br/>
                /// </summary>
                public sealed class IAsyncQueryBus_Generated : global::Demo.IAsyncQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IAsyncQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IAsyncQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Collections.Generic.IAsyncEnumerable<global::Demo.User> global::Demo.IAsyncQueryBus.SearchAsync(string query)
                    {
                        yield return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.DatabaseSearchHandler>(_serviceProvider).SearchAsync(query).ConfigureAwait(false);
                        yield return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CacheSearchHandler>(_serviceProvider).SearchAsync(query).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IAsyncQueryBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_Single_Handler_Per_Signature_Should_Not_Aggregate()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface IHandlers;

                public class HandlerAttribute : Attribute;

                public class CommandHandler
                {
                    [Handler]
                    public void CreateUser(CreateUserCommand command) { }

                    [Handler]
                    public void DeleteUser(DeleteUserCommand command) { }
                }

                public record CreateUserCommand(string Name);
                public record DeleteUserCommand(int UserId);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.CommandHandler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.CommandHandler.CreateUser(Demo.CreateUserCommand)"/>
                    /// </summary>
                    void CreateUser(global::Demo.CreateUserCommand command);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.CommandHandler.DeleteUser(Demo.DeleteUserCommand)"/>
                    /// </summary>
                    void DeleteUser(global::Demo.DeleteUserCommand command);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.CommandHandler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.CreateUser(global::Demo.CreateUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CommandHandler>(_serviceProvider).CreateUser(command);
                    }

                    void global::Demo.IHandlers.DeleteUser(global::Demo.DeleteUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CommandHandler>(_serviceProvider).DeleteUser(command);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expectedInterface));
    }
}
