using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;

namespace Terminus.Generator.Tests.Unit.Generator;

/// <summary>
/// Tests for TM0008 diagnostic - Multiple handlers with same signature when aggregation is disabled.
/// When AggregationMode is None (default), each signature must have exactly one handler.
/// </summary>
public class AggregationModeValidationTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_AggregationMode_None_With_Multiple_Handlers_Same_Signature_Should_Emit_TM0008()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.None)]
                public partial interface IHandlers;

                public class HandlerAttribute : Attribute;

                public class FirstHandler
                {
                    [Handler]
                    public void Handle(CreateUserCommand cmd) { }
                }

                public class SecondHandler
                {
                    [Handler]
                    public void Handle(CreateUserCommand cmd) { }
                }

                public record CreateUserCommand(string Name);
            }
            """;

        // Both handlers have the same signature, should report TM0008 for the second one
        var expectedDiagnostic = new DiagnosticResult("TM0008", DiagnosticSeverity.Error)
            .WithSpan("Source.cs", 20, 21, 20, 27) // SecondHandler.Handle
            .WithArguments("Handle(global::Demo.CreateUserCommand)");

        await VerifyAsync(source, [expectedDiagnostic]);
    }

    [Fact]
    public async Task Given_Default_AggregationMode_With_Multiple_Handlers_Same_Signature_Should_Emit_TM0008()
    {
        // Default AggregationMode is None, so this should also emit TM0008
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface IHandlers;

                public class HandlerAttribute : Attribute;

                public class FirstHandler
                {
                    [Handler]
                    public void Handle(CreateUserCommand cmd) { }
                }

                public class SecondHandler
                {
                    [Handler]
                    public void Handle(CreateUserCommand cmd) { }
                }

                public record CreateUserCommand(string Name);
            }
            """;

        var expectedDiagnostic = new DiagnosticResult("TM0008", DiagnosticSeverity.Error)
            .WithSpan("Source.cs", 20, 21, 20, 27) // SecondHandler.Handle
            .WithArguments("Handle(global::Demo.CreateUserCommand)");

        await VerifyAsync(source, [expectedDiagnostic]);
    }

    [Fact]
    public async Task Given_AggregationMode_None_With_Single_Handler_Per_Signature_Should_Generate_Successfully()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.None)]
                public partial interface IHandlers;

                public class HandlerAttribute : Attribute;

                public class UserHandlers
                {
                    [Handler]
                    public void CreateUser(CreateUserCommand cmd) { }

                    [Handler]
                    public void DeleteUser(DeleteUserCommand cmd) { }
                }

                public record CreateUserCommand(string Name);
                public record DeleteUserCommand(int Id);
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.CreateUser(Demo.CreateUserCommand)"/>
                    /// </summary>
                    void CreateUser(global::Demo.CreateUserCommand cmd);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.DeleteUser(Demo.DeleteUserCommand)"/>
                    /// </summary>
                    void DeleteUser(global::Demo.DeleteUserCommand cmd);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.CreateUser(global::Demo.CreateUserCommand cmd)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).CreateUser(cmd);
                    }

                    void global::Demo.IHandlers.DeleteUser(global::Demo.DeleteUserCommand cmd)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).DeleteUser(cmd);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_AggregationMode_Commands_With_Multiple_Void_Handlers_Should_Aggregate()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.Commands)]
                public partial interface INotificationBus;

                public class HandlerAttribute : Attribute;

                public class EmailHandler
                {
                    [Handler]
                    public void Handle(UserCreatedNotification notification) { }
                }

                public class LoggingHandler
                {
                    [Handler]
                    public void Handle(UserCreatedNotification notification) { }
                }

                public record UserCreatedNotification(int UserId);
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.EmailHandler"/><br/>
                /// <see cref="Demo.LoggingHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface INotificationBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.EmailHandler.Handle(Demo.UserCreatedNotification)"/><br/>
                    /// <see cref="Demo.LoggingHandler.Handle(Demo.UserCreatedNotification)"/>
                    /// </summary>
                    void Handle(global::Demo.UserCreatedNotification notification);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.INotificationBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.EmailHandler"/><br/>
                /// <see cref="Demo.LoggingHandler"/><br/>
                /// </summary>
                public sealed class INotificationBus_Generated : global::Demo.INotificationBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the INotificationBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public INotificationBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.INotificationBus.Handle(global::Demo.UserCreatedNotification notification)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.EmailHandler>(_serviceProvider).Handle(notification);
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.LoggingHandler>(_serviceProvider).Handle(notification);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_INotificationBus_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_AggregationMode_Commands_With_Multiple_Result_Handlers_Should_Emit_TM0008()
    {
        // AggregationMode.Commands only enables aggregation for void methods
        // Multiple result (non-void) handlers with same signature should still emit TM0008
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.Commands)]
                public partial interface IHandlers;

                public class HandlerAttribute : Attribute;

                public class FirstHandler
                {
                    [Handler]
                    public string Query(GetUserQuery query) => "First";
                }

                public class SecondHandler
                {
                    [Handler]
                    public string Query(GetUserQuery query) => "Second";
                }

                public record GetUserQuery(int Id);
            }
            """;

        var expectedDiagnostic = new DiagnosticResult("TM0008", DiagnosticSeverity.Error)
            .WithSpan("Source.cs", 20, 23, 20, 28) // SecondHandler.Query
            .WithArguments("Query(global::Demo.GetUserQuery)");

        await VerifyAsync(source, [expectedDiagnostic]);
    }

    [Fact]
    public async Task Given_AggregationMode_All_With_Multiple_Handlers_Should_Aggregate_All_Types()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.All)]
                public partial interface IQueryBus;

                public class HandlerAttribute : Attribute;

                public class PrimarySearchHandler
                {
                    [Handler]
                    public User Search(string query) => new User(1, "Primary");
                }

                public class SecondarySearchHandler
                {
                    [Handler]
                    public User Search(string query) => new User(2, "Secondary");
                }

                public record User(int Id, string Name);
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.PrimarySearchHandler"/><br/>
                /// <see cref="Demo.SecondarySearchHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.PrimarySearchHandler.Search(string)"/><br/>
                    /// <see cref="Demo.SecondarySearchHandler.Search(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<global::Demo.User> Search(string query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.PrimarySearchHandler"/><br/>
                /// <see cref="Demo.SecondarySearchHandler"/><br/>
                /// </summary>
                public sealed class IQueryBus_Generated : global::Demo.IQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<global::Demo.User> global::Demo.IQueryBus.Search(string query)
                    {
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.PrimarySearchHandler>(_serviceProvider).Search(query);
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.SecondarySearchHandler>(_serviceProvider).Search(query);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IQueryBus_Generated.g.cs", expected));
    }
}
