namespace Terminus.Generator.Tests.Unit.Generator;

/// <summary>
/// Tests for FacadeAggregationMode property parsing and storage.
/// Note: Aggregation feature is not yet implemented - these tests verify that the property
/// is correctly parsed from attributes and stored in FacadeInterfaceInfo.
/// </summary>
public class AggregationModeTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_AggregationMode_None_Should_Be_Parsed_And_Generate_Individual_Methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.None)]
                public partial interface IHandlers;

                public class HandlerAttribute : Attribute;

                public class UserHandlers
                {
                    [Handler]
                    public void CreateUser(CreateUserCommand command) { }

                    [Handler]
                    public string GetUser(GetUserQuery query) => "User";

                    [Handler]
                    public Task DeleteUserAsync(DeleteUserCommand command) => Task.CompletedTask;

                    [Handler]
                    public Task<int> GetUserCountAsync(GetUserCountQuery query) => Task.FromResult(42);
                }

                public record CreateUserCommand(string Name);
                public record GetUserQuery(int Id);
                public record DeleteUserCommand(int Id);
                public record GetUserCountQuery();
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.CreateUser(Demo.CreateUserCommand)"/>
                    /// </summary>
                    void CreateUser(global::Demo.CreateUserCommand command);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.GetUser(Demo.GetUserQuery)"/>
                    /// </summary>
                    string GetUser(global::Demo.GetUserQuery query);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.DeleteUserAsync(Demo.DeleteUserCommand)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task DeleteUserAsync(global::Demo.DeleteUserCommand command);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.GetUserCountAsync(Demo.GetUserCountQuery)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task<int> GetUserCountAsync(global::Demo.GetUserCountQuery query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.CreateUser(global::Demo.CreateUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).CreateUser(command);
                    }

                    string global::Demo.IHandlers.GetUser(global::Demo.GetUserQuery query)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).GetUser(query);
                    }

                    async global::System.Threading.Tasks.Task global::Demo.IHandlers.DeleteUserAsync(global::Demo.DeleteUserCommand command)
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).DeleteUserAsync(command).ConfigureAwait(false);
                    }

                    async global::System.Threading.Tasks.Task<int> global::Demo.IHandlers.GetUserCountAsync(global::Demo.GetUserCountQuery query)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).GetUserCountAsync(query).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_AggregationMode_Commands_Should_Be_Parsed()
    {
        // This test verifies that AggregationMode.Commands can be set without errors
        // Currently the feature is not implemented, so it behaves the same as None
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.Commands)]
                public partial interface ICommandBus;

                public class HandlerAttribute : Attribute;

                public class UserHandlers
                {
                    [Handler]
                    public void CreateUser(CreateUserCommand command) { }

                    [Handler]
                    public void DeleteUser(DeleteUserCommand command) { }
                }

                public record CreateUserCommand(string Name);
                public record DeleteUserCommand(int Id);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface ICommandBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.CreateUser(Demo.CreateUserCommand)"/>
                    /// </summary>
                    void CreateUser(global::Demo.CreateUserCommand command);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.UserHandlers.DeleteUser(Demo.DeleteUserCommand)"/>
                    /// </summary>
                    void DeleteUser(global::Demo.DeleteUserCommand command);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.ICommandBus))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.UserHandlers"/>
                /// </summary>
                public sealed class ICommandBus_Generated : global::Demo.ICommandBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the ICommandBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public ICommandBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.ICommandBus.CreateUser(global::Demo.CreateUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).CreateUser(command);
                    }

                    void global::Demo.ICommandBus.DeleteUser(global::Demo.DeleteUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.UserHandlers>(_serviceProvider).DeleteUser(command);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_ICommandBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_AggregationMode_All_Should_Be_Parsed()
    {
        // This test verifies that AggregationMode.All can be set without errors
        // Currently the feature is not implemented, so it behaves the same as None
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.All)]
                public partial interface IUniversalBus;

                public class HandlerAttribute : Attribute;

                public class Handlers
                {
                    [Handler]
                    public void CreateUser(CreateUserCommand command) { }

                    [Handler]
                    public string GetUser(GetUserQuery query) => "User";

                    [Handler]
                    public Task DeleteUserAsync(DeleteUserCommand command) => Task.CompletedTask;
                }

                public record CreateUserCommand(string Name);
                public record GetUserQuery(int Id);
                public record DeleteUserCommand(int Id);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IUniversalBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers.CreateUser(Demo.CreateUserCommand)"/>
                    /// </summary>
                    void CreateUser(global::Demo.CreateUserCommand command);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers.GetUser(Demo.GetUserQuery)"/>
                    /// </summary>
                    string GetUser(global::Demo.GetUserQuery query);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers.DeleteUserAsync(Demo.DeleteUserCommand)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task DeleteUserAsync(global::Demo.DeleteUserCommand command);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IUniversalBus))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handlers"/>
                /// </summary>
                public sealed class IUniversalBus_Generated : global::Demo.IUniversalBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IUniversalBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IUniversalBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IUniversalBus.CreateUser(global::Demo.CreateUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers>(_serviceProvider).CreateUser(command);
                    }

                    string global::Demo.IUniversalBus.GetUser(global::Demo.GetUserQuery query)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers>(_serviceProvider).GetUser(query);
                    }

                    async global::System.Threading.Tasks.Task global::Demo.IUniversalBus.DeleteUserAsync(global::Demo.DeleteUserCommand command)
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers>(_serviceProvider).DeleteUserAsync(command).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IUniversalBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_Combined_AggregationMode_Flags_Should_Be_Parsed()
    {
        // This test verifies that combined flags can be set without errors
        // Currently the feature is not implemented, so it behaves the same as None
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), AggregationMode = FacadeAggregationMode.Commands | FacadeAggregationMode.AsyncQueries)]
                public partial interface IHybridBus;

                public class HandlerAttribute : Attribute;

                public class Handlers
                {
                    [Handler]
                    public void CreateUser(CreateUserCommand command) { }

                    [Handler]
                    public Task<int> GetUserCountAsync(GetUserCountQuery query) => Task.FromResult(42);
                }

                public record CreateUserCommand(string Name);
                public record GetUserCountQuery();
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHybridBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers.CreateUser(Demo.CreateUserCommand)"/>
                    /// </summary>
                    void CreateUser(global::Demo.CreateUserCommand command);
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers.GetUserCountAsync(Demo.GetUserCountQuery)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task<int> GetUserCountAsync(global::Demo.GetUserCountQuery query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHybridBus))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handlers"/>
                /// </summary>
                public sealed class IHybridBus_Generated : global::Demo.IHybridBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHybridBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHybridBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHybridBus.CreateUser(global::Demo.CreateUserCommand command)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers>(_serviceProvider).CreateUser(command);
                    }

                    async global::System.Threading.Tasks.Task<int> global::Demo.IHybridBus.GetUserCountAsync(global::Demo.GetUserCountQuery query)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers>(_serviceProvider).GetUserCountAsync(query).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHybridBus_Generated.g.cs", expectedInterface));
    }
}
