using Microsoft.CodeAnalysis.Testing;

namespace Terminus.Generator.Tests.Unit.Generator;

/// <summary>
/// Tests for the AggregationReturnTypeStrategy feature.
/// When AggregationReturnTypeStrategy is First, aggregated methods return single results
/// instead of collections, executing only the first handler.
/// </summary>
public class AggregationReturnTypeStrategyTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_First_Strategy_With_Single_Result_Handler_Should_Return_Single_Result()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>(
                    AggregationMode = FacadeAggregationMode.Queries,
                    AggregationReturnTypeStrategy = AggregationReturnTypeStrategy.First)]
                public partial interface IQueryBus;

                public class HandlerAttribute : Attribute;

                public class SearchHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(1, "Result");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.SearchHandler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.SearchHandler.Search(string)"/>
                    /// </summary>
                    global::Demo.User Search(string query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.SearchHandler"/>
                /// </summary>
                public sealed class IQueryBus_Generated : global::Demo.IQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::Demo.User global::Demo.IQueryBus.Search(string query)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.SearchHandler>(_serviceProvider).Search(query);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IQueryBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_First_Strategy_With_Multiple_Result_Handlers_Should_Return_First_And_Emit_Warning()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>(
                    AggregationMode = FacadeAggregationMode.Queries,
                    AggregationReturnTypeStrategy = AggregationReturnTypeStrategy.First)]
                public partial interface IQueryBus;

                public class HandlerAttribute : Attribute;

                public class PrimarySearchHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(1, "Primary");
                    }
                }

                public class SecondarySearchHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(2, "Secondary");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.PrimarySearchHandler"/><br/>
                /// <see cref="Demo.SecondarySearchHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.PrimarySearchHandler.Search(string)"/><br/>
                    /// <see cref="Demo.SecondarySearchHandler.Search(string)"/>
                    /// </summary>
                    global::Demo.User Search(string query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.PrimarySearchHandler"/><br/>
                /// <see cref="Demo.SecondarySearchHandler"/><br/>
                /// </summary>
                public sealed class IQueryBus_Generated : global::Demo.IQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::Demo.User global::Demo.IQueryBus.Search(string query)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.PrimarySearchHandler>(_serviceProvider).Search(query);
                    }
                }
            }
            """;

        // Warning TM0010 is emitted - expect with location from actual test output
        var expectedDiagnostic = DiagnosticResult
            .CompilerWarning("TM0010")
            .WithSpan("/0/Test2.cs", 16, 21, 16, 27)
            .WithArguments("Search", "PrimarySearchHandler");

        await VerifyWithDiagnosticsAsync(source, new[] { expectedDiagnostic }, ("Demo_IQueryBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_First_Strategy_With_Async_Query_Should_Return_Task_Of_T()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>(
                    AggregationMode = FacadeAggregationMode.AsyncQueries,
                    AggregationReturnTypeStrategy = AggregationReturnTypeStrategy.First)]
                public partial interface IAsyncQueryBus;

                public class HandlerAttribute : Attribute;

                public class DatabaseHandler
                {
                    [Handler]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(1);
                        return new User(id, "User");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.DatabaseHandler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IAsyncQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.DatabaseHandler.GetUserAsync(int)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task<global::Demo.User> GetUserAsync(int id);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IAsyncQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.DatabaseHandler"/>
                /// </summary>
                public sealed class IAsyncQueryBus_Generated : global::Demo.IAsyncQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IAsyncQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IAsyncQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Threading.Tasks.Task<global::Demo.User> global::Demo.IAsyncQueryBus.GetUserAsync(int id)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.DatabaseHandler>(_serviceProvider).GetUserAsync(id).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IAsyncQueryBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_First_Strategy_With_Multiple_Async_Handlers_Should_Return_First_And_Emit_Warning()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>(
                    AggregationMode = FacadeAggregationMode.AsyncQueries,
                    AggregationReturnTypeStrategy = AggregationReturnTypeStrategy.First)]
                public partial interface IAsyncQueryBus;

                public class HandlerAttribute : Attribute;

                public class DatabaseHandler
                {
                    [Handler]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(1);
                        return new User(id, "DB User");
                    }
                }

                public class CacheHandler
                {
                    [Handler]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(1);
                        return new User(id, "Cached User");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.CacheHandler"/><br/>
                /// <see cref="Demo.DatabaseHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IAsyncQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.DatabaseHandler.GetUserAsync(int)"/><br/>
                    /// <see cref="Demo.CacheHandler.GetUserAsync(int)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task<global::Demo.User> GetUserAsync(int id);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IAsyncQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.CacheHandler"/><br/>
                /// <see cref="Demo.DatabaseHandler"/><br/>
                /// </summary>
                public sealed class IAsyncQueryBus_Generated : global::Demo.IAsyncQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IAsyncQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IAsyncQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Threading.Tasks.Task<global::Demo.User> global::Demo.IAsyncQueryBus.GetUserAsync(int id)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.DatabaseHandler>(_serviceProvider).GetUserAsync(id).ConfigureAwait(false);
                    }
                }
            }
            """;

        // Warning TM0010 is emitted - expect with location from actual test output
        var expectedDiagnostic = DiagnosticResult
            .CompilerWarning("TM0010")
            .WithSpan("/0/Test2.cs", 17, 33, 17, 45)
            .WithArguments("GetUserAsync", "DatabaseHandler");

        await VerifyWithDiagnosticsAsync(source, new[] { expectedDiagnostic }, ("Demo_IAsyncQueryBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_First_Strategy_With_Void_Commands_Should_Execute_First_Only()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>(
                    AggregationMode = FacadeAggregationMode.Commands,
                    AggregationReturnTypeStrategy = AggregationReturnTypeStrategy.First)]
                public partial interface ICommandBus;

                public class HandlerAttribute : Attribute;

                public class PrimaryHandler
                {
                    [Handler]
                    public void Execute(Command cmd)
                    {
                        Console.WriteLine("Primary");
                    }
                }

                public class SecondaryHandler
                {
                    [Handler]
                    public void Execute(Command cmd)
                    {
                        Console.WriteLine("Secondary");
                    }
                }

                public record Command(string Data);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.PrimaryHandler"/><br/>
                /// <see cref="Demo.SecondaryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface ICommandBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.PrimaryHandler.Execute(Demo.Command)"/><br/>
                    /// <see cref="Demo.SecondaryHandler.Execute(Demo.Command)"/>
                    /// </summary>
                    void Execute(global::Demo.Command cmd);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.ICommandBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.PrimaryHandler"/><br/>
                /// <see cref="Demo.SecondaryHandler"/><br/>
                /// </summary>
                public sealed class ICommandBus_Generated : global::Demo.ICommandBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the ICommandBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public ICommandBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.ICommandBus.Execute(global::Demo.Command cmd)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.PrimaryHandler>(_serviceProvider).Execute(cmd);
                    }
                }
            }
            """;

        // No warning for void methods as they don't return values
        await VerifyAsync(source, ("Demo_ICommandBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_First_Strategy_With_Async_Commands_Should_Execute_First_Only()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>(
                    AggregationMode = FacadeAggregationMode.AsyncCommands,
                    AggregationReturnTypeStrategy = AggregationReturnTypeStrategy.First)]
                public partial interface IAsyncCommandBus;

                public class HandlerAttribute : Attribute;

                public class PrimaryHandler
                {
                    [Handler]
                    public async Task ExecuteAsync(Command cmd)
                    {
                        await Task.Delay(1);
                        Console.WriteLine("Primary");
                    }
                }

                public class SecondaryHandler
                {
                    [Handler]
                    public async Task ExecuteAsync(Command cmd)
                    {
                        await Task.Delay(1);
                        Console.WriteLine("Secondary");
                    }
                }

                public record Command(string Data);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.PrimaryHandler"/><br/>
                /// <see cref="Demo.SecondaryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IAsyncCommandBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.PrimaryHandler.ExecuteAsync(Demo.Command)"/><br/>
                    /// <see cref="Demo.SecondaryHandler.ExecuteAsync(Demo.Command)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task ExecuteAsync(global::Demo.Command cmd);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IAsyncCommandBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.PrimaryHandler"/><br/>
                /// <see cref="Demo.SecondaryHandler"/><br/>
                /// </summary>
                public sealed class IAsyncCommandBus_Generated : global::Demo.IAsyncCommandBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IAsyncCommandBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IAsyncCommandBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Threading.Tasks.Task global::Demo.IAsyncCommandBus.ExecuteAsync(global::Demo.Command cmd)
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.PrimaryHandler>(_serviceProvider).ExecuteAsync(cmd).ConfigureAwait(false);
                    }
                }
            }
            """;

        // No warning for Task (void) methods as they don't return values
        await VerifyAsync(source, ("Demo_IAsyncCommandBus_Generated.g.cs", expectedInterface));
    }

    [Fact]
    public async Task Given_Collection_Strategy_Default_Should_Return_Collection()
    {
        // This test verifies backward compatibility - Collection is the default
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                [FacadeOf<HandlerAttribute>( AggregationMode = FacadeAggregationMode.Queries)]
                public partial interface IQueryBus;

                public class HandlerAttribute : Attribute;

                public class PrimaryHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(1, "Primary");
                    }
                }

                public class SecondaryHandler
                {
                    [Handler]
                    public User Search(string query)
                    {
                        return new User(2, "Secondary");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expectedInterface =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.PrimaryHandler"/><br/>
                /// <see cref="Demo.SecondaryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IQueryBus
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.PrimaryHandler.Search(string)"/><br/>
                    /// <see cref="Demo.SecondaryHandler.Search(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<global::Demo.User> Search(string query);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IQueryBus))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.PrimaryHandler"/><br/>
                /// <see cref="Demo.SecondaryHandler"/><br/>
                /// </summary>
                public sealed class IQueryBus_Generated : global::Demo.IQueryBus
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IQueryBus_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IQueryBus_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<global::Demo.User> global::Demo.IQueryBus.Search(string query)
                    {
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.PrimaryHandler>(_serviceProvider).Search(query);
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.SecondaryHandler>(_serviceProvider).Search(query);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IQueryBus_Generated.g.cs", expectedInterface));
    }
}
