#pragma warning disable CS0162 // Unreachable code detected
namespace Terminus.Generator.Tests.Unit.Generator;

/// <summary>
/// Tests for attribute metadata inclusion with lazy execution in facade methods.
/// When IncludeAttributeMetadata = true, facade methods return IEnumerable of tuples containing
/// the attribute instance and a delegate (Func or Action) that can be invoked to execute the handler.
/// This enables filtering handlers based on attribute properties before execution.
/// Works with single methods and aggregated methods alike.
/// </summary>
public class AttributeMetadataTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_aggregated_methods_with_metadata_enabled_Should_return_lazy_tuple_with_common_base()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public abstract class HandlerAttribute : Attribute
                {
                    public string Name { get; }
                    protected HandlerAttribute(string name) => Name = name;
                }

                public class CommandAttribute : HandlerAttribute
                {
                    public CommandAttribute(string name) : base(name) { }
                }

                public class QueryAttribute : HandlerAttribute
                {
                    public QueryAttribute(string name) : base(name) { }
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handlers1
                {
                    [Command("Create")]
                    public string Process(string input) => "cmd";
                }

                public class Handlers2
                {
                    [Query("Get")]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handlers1"/><br/>
                /// <see cref="Demo.Handlers2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers1.Process(string)"/><br/>
                    /// <see cref="Demo.Handlers2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handlers1"/><br/>
                /// <see cref="Demo.Handlers2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.CommandAttribute("Create"), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.QueryAttribute("Get"), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_aggregated_methods_without_metadata_flag_Should_return_results_only()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler]
                    public string Process(string input) => "result1";
                }

                public class Handler2
                {
                    [Handler]
                    public string Process(string input) => "result2";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<string> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<string> global::Demo.IHandlers.Process(string input)
                    {
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input);
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_aggregated_methods_with_no_common_base_Should_return_lazy_tuple_with_System_Attribute()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class CommandAttribute : Attribute { }
                public class QueryAttribute : Attribute { }

                [FacadeOf(typeof(CommandAttribute), typeof(QueryAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class CommandHandler
                {
                    [Command]
                    public string Process(string input) => "cmd";
                }

                public class QueryHandler
                {
                    [Query]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.CommandHandler.Process(string)"/><br/>
                    /// <see cref="Demo.QueryHandler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::System.Attribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::System.Attribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.CommandAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CommandHandler>(_serviceProvider).Process(input));
                        yield return (new global::Demo.QueryAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.QueryHandler>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_void_aggregated_methods_with_metadata_Should_return_Action_tuple()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler]
                    public void Process(string input) { }
                }

                public class Handler2
                {
                    [Handler]
                    public void Process(string input) { }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Action Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Action Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () =>
                        {
                            global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input);
                        });
                        yield return (new global::Demo.HandlerAttribute(), () =>
                        {
                            global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input);
                        });
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_Task_aggregated_methods_with_metadata_Should_return_FuncTask_tuple()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler]
                    public async Task ProcessAsync(string input) => await Task.CompletedTask;
                }

                public class Handler2
                {
                    [Handler]
                    public async Task ProcessAsync(string input) => await Task.CompletedTask;
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.ProcessAsync(string)"/><br/>
                    /// <see cref="Demo.Handler2.ProcessAsync(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.Task> Handler)> ProcessAsync(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.Task> Handler)> global::Demo.IHandlers.ProcessAsync(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).ProcessAsync(input));
                        yield return (new global::Demo.HandlerAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).ProcessAsync(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_async_result_aggregated_methods_with_metadata_Should_return_FuncTaskT_tuple()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public int Priority { get; }
                    public HandlerAttribute(int priority) => Priority = priority;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler(1)]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(10);
                        return new User(id, "User1");
                    }
                }

                public class Handler2
                {
                    [Handler(2)]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(5);
                        return new User(id, "User2");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.GetUserAsync(int)"/><br/>
                    /// <see cref="Demo.Handler2.GetUserAsync(int)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.Task<global::Demo.User>> Handler)> GetUserAsync(int id);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.Task<global::Demo.User>> Handler)> global::Demo.IHandlers.GetUserAsync(int id)
                    {
                        yield return (new global::Demo.HandlerAttribute(1), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).GetUserAsync(id));
                        yield return (new global::Demo.HandlerAttribute(2), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).GetUserAsync(id));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_single_attribute_type_with_metadata_Should_use_exact_attribute_type()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public string Name { get; }
                    public HandlerAttribute(string name) => Name = name;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler("First")]
                    public string Process(string input) => "result1";
                }

                public class Handler2
                {
                    [Handler("Second")]
                    public string Process(string input) => "result2";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute("First"), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.HandlerAttribute("Second"), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_deeper_hierarchy_with_metadata_Should_use_most_derived_common_base()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public abstract class HandlerAttribute : Attribute { }
                public abstract class SyncHandlerAttribute : HandlerAttribute { }

                public class CommandAttribute : SyncHandlerAttribute { }
                public class QueryAttribute : SyncHandlerAttribute { }

                [FacadeOf(typeof(CommandAttribute), typeof(QueryAttribute), IncludeAttributeMetadata = true)]
                public partial interface ISyncHandlers;

                public class CommandHandler
                {
                    [Command]
                    public string Process(string input) => "cmd";
                }

                public class QueryHandler
                {
                    [Query]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface ISyncHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.CommandHandler.Process(string)"/><br/>
                    /// <see cref="Demo.QueryHandler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.SyncHandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.ISyncHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                public sealed class ISyncHandlers_Generated : global::Demo.ISyncHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the ISyncHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public ISyncHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.SyncHandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.ISyncHandlers.Process(string input)
                    {
                        yield return (new global::Demo.CommandAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CommandHandler>(_serviceProvider).Process(input));
                        yield return (new global::Demo.QueryAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.QueryHandler>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_ISyncHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_attribute_with_named_properties_Should_reconstruct_attribute_correctly()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public string Name { get; set; } = "";
                    public int Priority { get; set; }
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler(Name = "First", Priority = 1)]
                    public string Process(string input) => "result1";
                }

                public class Handler2
                {
                    [Handler(Name = "Second", Priority = 2)]
                    public string Process(string input) => "result2";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute { Name = "First", Priority = 1 }, () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.HandlerAttribute { Name = "Second", Priority = 2 }, () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_attribute_with_enum_argument_Should_reconstruct_attribute_correctly()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public enum HandlerType { Command, Query }

                public class HandlerAttribute : Attribute
                {
                    public HandlerType Type { get; }
                    public HandlerAttribute(HandlerType type) => Type = type;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler(HandlerType.Command)]
                    public string Process(string input) => "cmd";
                }

                public class Handler2
                {
                    [Handler(HandlerType.Query)]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute((global::Demo.HandlerType)0), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.HandlerAttribute((global::Demo.HandlerType)1), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_single_method_with_metadata_Should_return_lazy_tuple()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public string Name { get; }
                    public HandlerAttribute(string name) => Name = name;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler
                {
                    [Handler("OnlyOne")]
                    public string Process(string input) => "result";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute("OnlyOne"), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_single_void_method_with_metadata_Should_return_Action_tuple()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler
                {
                    [Handler]
                    public void Process(string input) { }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Action Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Action Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () =>
                        {
                            global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler>(_serviceProvider).Process(input);
                        });
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    [Trait("Category", "RequiresCoreRuntime")]
    public async Task Given_ValueTask_method_with_metadata_Should_return_FuncValueTask_tuple()
    {
#if NET472
        // Skip on .NET Framework 4.7.2 - ValueTask doesn't exist
        await Task.CompletedTask;
        return;
#endif
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler
                {
                    [Handler]
                    public ValueTask ProcessAsync(string input) => new ValueTask();
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler.ProcessAsync(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.ValueTask> Handler)> ProcessAsync(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.ValueTask> Handler)> global::Demo.IHandlers.ProcessAsync(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler>(_serviceProvider).ProcessAsync(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    [Trait("Category", "RequiresCoreRuntime")]
    public async Task Given_ValueTaskT_method_with_metadata_Should_return_FuncValueTaskT_tuple()
    {
#if NET472
        // Skip on .NET Framework 4.7.2 - ValueTask.FromResult doesn't exist
        await Task.CompletedTask;
        return;
#endif
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler
                {
                    [Handler]
                    public ValueTask<string> ProcessAsync(string input) => ValueTask.FromResult(input);
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler.ProcessAsync(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.ValueTask<string>> Handler)> ProcessAsync(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Threading.Tasks.ValueTask<string>> Handler)> global::Demo.IHandlers.ProcessAsync(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler>(_serviceProvider).ProcessAsync(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_IAsyncEnumerable_method_with_metadata_Should_return_Func_tuple()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler
                {
                    [Handler]
                    public async IAsyncEnumerable<string> StreamAsync(string input)
                    {
                        yield return input;
                    }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler.StreamAsync(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Collections.Generic.IAsyncEnumerable<string>> Handler)> StreamAsync(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<global::System.Collections.Generic.IAsyncEnumerable<string>> Handler)> global::Demo.IHandlers.StreamAsync(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler>(_serviceProvider).StreamAsync(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_static_method_with_metadata_Should_call_directly()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public static class StaticHandler
                {
                    [Handler]
                    public static string Process(string input) => input.ToUpper();
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.StaticHandler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.StaticHandler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.StaticHandler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, global::System.Func<string> Handler)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute(), () => global::Demo.StaticHandler.Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }
}
