namespace Terminus.Generator.Tests.Unit.Generator;

/// <summary>
/// Tests for attribute metadata inclusion in aggregated method results.
/// When IncludeAttributeMetadata = true, aggregated methods return tuples containing
/// both the attribute instance and the result.
/// </summary>
public class AttributeMetadataTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_aggregated_methods_with_metadata_enabled_Should_return_tuple_with_common_base()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public abstract class HandlerAttribute : Attribute
                {
                    public string Name { get; }
                    protected HandlerAttribute(string name) => Name = name;
                }

                public class CommandAttribute : HandlerAttribute
                {
                    public CommandAttribute(string name) : base(name) { }
                }

                public class QueryAttribute : HandlerAttribute
                {
                    public QueryAttribute(string name) : base(name) { }
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handlers1
                {
                    [Command("Create")]
                    public string Process(string input) => "cmd";
                }

                public class Handlers2
                {
                    [Query("Get")]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handlers1"/><br/>
                /// <see cref="Demo.Handlers2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handlers1.Process(string)"/><br/>
                    /// <see cref="Demo.Handlers2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handlers1"/><br/>
                /// <see cref="Demo.Handlers2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.CommandAttribute("Create"), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.QueryAttribute("Get"), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handlers2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_aggregated_methods_without_metadata_flag_Should_return_results_only()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute))]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler]
                    public string Process(string input) => "result1";
                }

                public class Handler2
                {
                    [Handler]
                    public string Process(string input) => "result2";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<string> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<string> global::Demo.IHandlers.Process(string input)
                    {
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input);
                        yield return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_aggregated_methods_with_no_common_base_Should_return_tuple_with_System_Attribute()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class CommandAttribute : Attribute { }
                public class QueryAttribute : Attribute { }

                [FacadeOf(typeof(CommandAttribute), typeof(QueryAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class CommandHandler
                {
                    [Command]
                    public string Process(string input) => "cmd";
                }

                public class QueryHandler
                {
                    [Query]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.CommandHandler.Process(string)"/><br/>
                    /// <see cref="Demo.QueryHandler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::System.Attribute Attribute, string Result)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::System.Attribute Attribute, string Result)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.CommandAttribute(), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CommandHandler>(_serviceProvider).Process(input));
                        yield return (new global::Demo.QueryAttribute(), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.QueryHandler>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_void_aggregated_methods_with_metadata_Should_not_return_tuple()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler]
                    public void Process(string input) { }
                }

                public class Handler2
                {
                    [Handler]
                    public void Process(string input) { }
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    void Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.Process(string input)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input);
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_Task_aggregated_methods_with_metadata_Should_not_return_tuple()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute { }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler]
                    public async Task ProcessAsync(string input) => await Task.CompletedTask;
                }

                public class Handler2
                {
                    [Handler]
                    public async Task ProcessAsync(string input) => await Task.CompletedTask;
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.ProcessAsync(string)"/><br/>
                    /// <see cref="Demo.Handler2.ProcessAsync(string)"/>
                    /// </summary>
                    global::System.Threading.Tasks.Task ProcessAsync(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Threading.Tasks.Task global::Demo.IHandlers.ProcessAsync(string input)
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).ProcessAsync(input).ConfigureAwait(false);
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).ProcessAsync(input).ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_async_result_aggregated_methods_with_metadata_Should_return_async_enumerable_tuple()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public int Priority { get; }
                    public HandlerAttribute(int priority) => Priority = priority;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler(1)]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(10);
                        return new User(id, "User1");
                    }
                }

                public class Handler2
                {
                    [Handler(2)]
                    public async Task<User> GetUserAsync(int id)
                    {
                        await Task.Delay(5);
                        return new User(id, "User2");
                    }
                }

                public record User(int Id, string Name);
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.GetUserAsync(int)"/><br/>
                    /// <see cref="Demo.Handler2.GetUserAsync(int)"/>
                    /// </summary>
                    global::System.Collections.Generic.IAsyncEnumerable<(global::Demo.HandlerAttribute Attribute, global::Demo.User Result)> GetUserAsync(int id);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Collections.Generic.IAsyncEnumerable<(global::Demo.HandlerAttribute Attribute, global::Demo.User Result)> global::Demo.IHandlers.GetUserAsync(int id)
                    {
                        yield return (new global::Demo.HandlerAttribute(1), await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).GetUserAsync(id).ConfigureAwait(false));
                        yield return (new global::Demo.HandlerAttribute(2), await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).GetUserAsync(id).ConfigureAwait(false));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_single_attribute_type_with_metadata_Should_use_exact_attribute_type()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public string Name { get; }
                    public HandlerAttribute(string name) => Name = name;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler("First")]
                    public string Process(string input) => "result1";
                }

                public class Handler2
                {
                    [Handler("Second")]
                    public string Process(string input) => "result2";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute("First"), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.HandlerAttribute("Second"), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_deeper_hierarchy_with_metadata_Should_use_most_derived_common_base()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public abstract class HandlerAttribute : Attribute { }
                public abstract class SyncHandlerAttribute : HandlerAttribute { }

                public class CommandAttribute : SyncHandlerAttribute { }
                public class QueryAttribute : SyncHandlerAttribute { }

                [FacadeOf(typeof(CommandAttribute), typeof(QueryAttribute), IncludeAttributeMetadata = true)]
                public partial interface ISyncHandlers;

                public class CommandHandler
                {
                    [Command]
                    public string Process(string input) => "cmd";
                }

                public class QueryHandler
                {
                    [Query]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface ISyncHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.CommandHandler.Process(string)"/><br/>
                    /// <see cref="Demo.QueryHandler.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.SyncHandlerAttribute Attribute, string Result)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.ISyncHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.CommandHandler"/><br/>
                /// <see cref="Demo.QueryHandler"/><br/>
                /// </summary>
                public sealed class ISyncHandlers_Generated : global::Demo.ISyncHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the ISyncHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public ISyncHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.SyncHandlerAttribute Attribute, string Result)> global::Demo.ISyncHandlers.Process(string input)
                    {
                        yield return (new global::Demo.CommandAttribute(), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.CommandHandler>(_serviceProvider).Process(input));
                        yield return (new global::Demo.QueryAttribute(), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.QueryHandler>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_ISyncHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_attribute_with_named_properties_Should_reconstruct_attribute_correctly()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public string Name { get; set; } = "";
                    public int Priority { get; set; }
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler(Name = "First", Priority = 1)]
                    public string Process(string input) => "result1";
                }

                public class Handler2
                {
                    [Handler(Name = "Second", Priority = 2)]
                    public string Process(string input) => "result2";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute { Name = "First", Priority = 1 }, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.HandlerAttribute { Name = "Second", Priority = 2 }, global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_attribute_with_enum_argument_Should_reconstruct_attribute_correctly()
    {
        const string source =
            """
            using System;
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                public enum HandlerType { Command, Query }

                public class HandlerAttribute : Attribute
                {
                    public HandlerType Type { get; }
                    public HandlerAttribute(HandlerType type) => Type = type;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler1
                {
                    [Handler(HandlerType.Command)]
                    public string Process(string input) => "cmd";
                }

                public class Handler2
                {
                    [Handler(HandlerType.Query)]
                    public string Process(string input) => "qry";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler1.Process(string)"/><br/>
                    /// <see cref="Demo.Handler2.Process(string)"/>
                    /// </summary>
                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to:<br/>
                /// <see cref="Demo.Handler1"/><br/>
                /// <see cref="Demo.Handler2"/><br/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    global::System.Collections.Generic.IEnumerable<(global::Demo.HandlerAttribute Attribute, string Result)> global::Demo.IHandlers.Process(string input)
                    {
                        yield return (new global::Demo.HandlerAttribute((global::Demo.HandlerType)0), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler1>(_serviceProvider).Process(input));
                        yield return (new global::Demo.HandlerAttribute((global::Demo.HandlerType)1), global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler2>(_serviceProvider).Process(input));
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_non_aggregated_method_with_metadata_Should_not_affect_single_method()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                public class HandlerAttribute : Attribute
                {
                    public string Name { get; }
                    public HandlerAttribute(string name) => Name = name;
                }

                [FacadeOf(typeof(HandlerAttribute), IncludeAttributeMetadata = true)]
                public partial interface IHandlers;

                public class Handler
                {
                    [Handler("OnlyOne")]
                    public string Process(string input) => "result";
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.Handler.Process(string)"/>
                    /// </summary>
                    string Process(string input);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.Handler"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    string global::Demo.IHandlers.Process(string input)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.Handler>(_serviceProvider).Process(input);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IHandlers_Generated.g.cs", expected));
    }
}
