using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Testing;

namespace Terminus.Generator.Tests.Unit.Generator;

public class EdgeCaseTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_In_Parameter_Should_Report_Diagnostic()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute))]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestHandlers
                {
                    [FacadeMethod]
                    public void MethodWithIn(in int value)
                    {
                    }
                }
            }
            """;

        var expectedDiagnostic = new DiagnosticResult("TM0002", DiagnosticSeverity.Error)
            .WithSpan("Source.cs", 14, 34, 14, 36)
            .WithArguments("MethodWithIn", "value");

        await VerifyAsync(source, [expectedDiagnostic]);
    }

    [Fact]
    public async Task Given_Default_Values_Should_Include_Them_In_Signature()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute))]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestHandlers
                {
                    [FacadeMethod]
                    public void MethodWithDefault(string name = "Junie", int age = 20)
                    {
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.TestHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IFacade
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestHandlers.MethodWithDefault(string, int)"/>
                    /// </summary>
                    void MethodWithDefault(string name = "Junie", int age = 20);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.TestHandlers"/>
                /// </summary>
                public sealed class IFacade_Generated : global::Demo.IFacade
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IFacade_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IFacade.MethodWithDefault(string name = "Junie", int age = 20)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestHandlers>(_serviceProvider).MethodWithDefault(name, age);
                    }
                }
            }
            """;

        await VerifyAsync(
            source,
            ("Demo_IFacade_Generated.g.cs", expectedMainSource));
    }

    [Fact]
    public async Task Given_Reserved_Keywords_Should_Escape_Them()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute))]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestHandlers
                {
                    [FacadeMethod]
                    public void MethodWithReserved<@class>(string @event)
                    {
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.TestHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IFacade
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestHandlers.MethodWithReserved(string)"/>
                    /// </summary>
                    void MethodWithReserved<@class>(string @event);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.TestHandlers"/>
                /// </summary>
                public sealed class IFacade_Generated : global::Demo.IFacade
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IFacade_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IFacade.MethodWithReserved<@class>(string @event)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestHandlers>(_serviceProvider).MethodWithReserved<@class>(@event);
                    }
                }
            }
            """;

        await VerifyAsync(
            source,
            ("Demo_IFacade_Generated.g.cs", expectedMainSource));
    }

    [Fact]
    public async Task Given_Duplicate_Signatures_Should_Aggregate_Methods()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), CommandName="Process", AggregationMode = FacadeAggregationMode.Commands)]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestHandlers
                {
                    [FacadeMethod]
                    public void ProcessOne(int value) {}

                    [FacadeMethod]
                    public void ProcessTwo(int value) {}
                }
            }
            """;

        const string expected =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.TestHandlers"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IFacade
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestHandlers.ProcessOne(int)"/><br/>
                    /// <see cref="Demo.TestHandlers.ProcessTwo(int)"/>
                    /// </summary>
                    void Process(int value);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="Demo.TestHandlers"/>
                /// </summary>
                public sealed class IFacade_Generated : global::Demo.IFacade
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IFacade_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IFacade.Process(int value)
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestHandlers>(_serviceProvider).ProcessOne(value);
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestHandlers>(_serviceProvider).ProcessTwo(value);
                    }
                }
            }
            """;

        await VerifyAsync(source, ("Demo_IFacade_Generated.g.cs", expected));
    }

    [Fact]
    public async Task Given_Conflicting_Parameter_Name_Should_Report_Diagnostic()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute))]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestHandlers
                {
                    [FacadeMethod]
                    public void ConflictingMethod(string _serviceProvider)
                    {
                    }
                }
            }
            """;

        var expectedDiagnostic = new DiagnosticResult("TM0003", DiagnosticSeverity.Error)
            .WithSpan("Source.cs", 14, 46, 14, 62)
            .WithArguments("_serviceProvider", "ConflictingMethod");

        await VerifyAsync(source, [expectedDiagnostic]);
    }
}
