using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class EntryPointDiscoveryGeneratorAgnosticTests
{
    [Fact]
    public async Task Given_entry_point_methods_with_same_signature_but_in_different_types_When_one_set_of_methods_are_not_aggregate_Should_not_generate_duplicate_entry_point_diagnostic()
    {
        // An entry point not used in an aggregator (i.e. mediator or facade)
        // does not have an EntryPointDescriptor di registration generated
        const string source =
            """
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [ScopedEntryPointFacade(typeof(TestEntryPoints))]
                public partial interface IFacade;

                public static class TestEntryPoints
                {
                    [EntryPoint]
                    public static void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"hello {world}");
                    }
                }

                public class MyService
                {
                    // duplicate signature in TestEntryPoints should not create diagnostics because of
                    // the attribute constructor arg [ScopedEntryPointFacade(typeof(TestEntryPoints))]
                    [EntryPoint]
                    public void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"service hello {world}");
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;

            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, System.Threading.CancellationToken cancellationToken);
                }

                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IFacade> _dispatcher;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }

                    public void Hello(string world, System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        Demo.TestEntryPoints.Hello(world, cancellationToken);
                    }
                }
            }

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointsFor_Demo_IFacade(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var resolver = new Terminus.ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IEntryPointRouter<Demo.IFacade>, DefaultEntryPointRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string), typeof(System.Threading.CancellationToken) })!, (context, ct) => Demo.TestEntryPoints.Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context), ct)));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPoints<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddEntryPointsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }

                    public static IServiceCollection AddEntryPoints(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
}
