using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class EntryPointDiscoveryGeneratorMediatorTests
{
    [Fact]
    public async Task Given_the_presence_of_the_mediator_attribute_Should_not_generate_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [EntryPointMediator(EntryPointAttributes = [typeof(MyEntryPointAttribute)])]
                public partial interface IMediator;

                public class MyEntryPointAttribute : EntryPointAttribute;

                public class TestEntryPoints
                {
                    [MyEntryPoint]
                    public void Hello()
                    {
                    }

                    [MyEntryPoint]
                    public  string Hello(string world)
                    {
                        return world;
                    }

                    [MyEntryPoint]
                    public Task HelloAsync()
                    {
                        return Task.CompletedTask;
                    }

                    [MyEntryPoint]
                    public async Task<string> HelloAsync(string world)
                    {
                        return await Task.FromResult(world);
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;

            namespace Demo
            {
                public partial interface IMediator
                {
                    void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default);
                    T Send<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task PublishAsync(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task<T> SendAsync<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default);
                }

                internal sealed class IMediator_Generated : Demo.IMediator
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IMediator> _dispatcher;
                    public IMediator_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IMediator> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }

                    public void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _dispatcher.Publish(context, cancellationToken);
                    }

                    public T Send<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.Send<T>(context, cancellationToken);
                    }

                    public System.Threading.Tasks.Task PublishAsync(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.PublishAsync(context, cancellationToken);
                    }

                    public System.Threading.Tasks.Task<T> SendAsync<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.SendAsync<T>(context, cancellationToken);
                    }
                }
            }

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointsFor_Demo_IMediator(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new Terminus.ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<Dispatcher<Demo.IMediator>>();
                        services.AddTransient<IEntryPointRouter<Demo.IMediator>, DefaultEntryPointRouter<Demo.IMediator>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IMediator), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello()));
                        services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IMediator), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context))));
                        services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IMediator), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloAsync", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync()));
                        services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IMediator), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloAsync", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestEntryPoints>();
                        services.AddSingleton<Demo.IMediator, Demo.IMediator_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPoints<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IMediator":
                                return services.AddEntryPointsFor_Demo_IMediator(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }

                    public static IServiceCollection AddEntryPoints(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointsFor_Demo_IMediator();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "Demo_IMediator_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));


        await test.RunAsync();
    }

    [Fact]
    public async Task Given_ScopedEntryPointMediator_with_custom_attribute_Should_generate_AddEntryPoints_not_AddEntryPointMediator()
    {
        const string source =
            """
            using System;
            using Microsoft.Extensions.DependencyInjection;
            using Terminus;

            namespace Demo
            {
                [ScopedEntryPointMediator(EntryPointAttributes = [typeof(MyCustomAttribute)])]
                public partial interface IDispatcher;

                [AttributeUsage(AttributeTargets.Method)]
                public class MyCustomAttribute(string path) : EntryPointAttribute
                {
                    public string Path { get; } = path;
                }

                public class MyController
                {
                    [MyCustomAttribute("/users/{id}")]
                    public void GetUser(string id) { }
                }

                public class Program
                {
                    public static void Main()
                    {
                        var services = new ServiceCollection();

                        // This should fail because the generated method is AddEntryPoints, not AddEntryPointMediator
                        services.AddEntryPoints<IDispatcher>();
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;

            namespace Demo
            {
                public partial interface IDispatcher
                {
                    void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default);
                }

                internal sealed class IDispatcher_Generated : Demo.IDispatcher
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IDispatcher> _dispatcher;
                    public IDispatcher_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IDispatcher> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }

                    public void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments,, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        using (var scope = _serviceProvider.CreateScope())
                        {
                            _dispatcher.Publish(context, cancellationToken);
                        }
                    }
                }
            }

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointsFor_Demo_IDispatcher(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new Terminus.ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<Dispatcher<Demo.IDispatcher>>();
                        services.AddTransient<IEntryPointRouter<Demo.IDispatcher>, DefaultEntryPointRouter<Demo.IDispatcher>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyCustomAttribute>>(typeof(Demo.IDispatcher), (provider, key) => new EntryPointDescriptor<Demo.MyCustomAttribute>(typeof(Demo.MyController).GetMethod("GetUser", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.MyController>().GetUser(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("id", context))));
                        services.AddTransient<Demo.MyController>();
                        services.AddSingleton<Demo.IDispatcher, Demo.IDispatcher_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPoints<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IDispatcher":
                                return services.AddEntryPointsFor_Demo_IDispatcher(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }

                    public static IServiceCollection AddEntryPoints(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointsFor_Demo_IDispatcher();
                        return services;
                    }
                }
            }
            """;

        var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "Demo_IDispatcher_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();

        await test.RunAsync();
    }
}
