using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class EntryPointDiscoveryGeneratorTests
{
    [Fact]
    public async Task Given_a_single_parameter_method_Should_generate_entry_point_command()
    {
        const string source =
            """
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [ScopedEntryPointFacade]
                public partial interface IFacade;
                
                public static class TestEntryPoints
                {
                    [EntryPoint]
                    public static void Hello(string world, CancellationToken cancellationToken) 
                    { 
                        Console.WriteLine($"hello {world}"); 
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, System.Threading.CancellationToken cancellationToken);
                    void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IFacade> _dispatcher;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }
            
                    public void Hello(string world, System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        Demo.TestEntryPoints.Hello(world, cancellationToken);
                    }
            
                    public void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _dispatcher.Publish(context, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointFacadeFor_Demo_IFacade(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<ScopedDispatcher<Demo.IFacade>>();
                        services.AddTransient<IEntryPointRouter<Demo.IFacade>, DefaultEntryPointRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string), typeof(System.Threading.CancellationToken) })!, (context, ct) => Demo.TestEntryPoints.Hello(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context), ct)));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPointFacade<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                        where T : EntryPointAttribute
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddEntryPointFacadeFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"No entry point discovery strategy found for type '{typeof(T).FullName}'");
                    }
            
                    public static IServiceCollection AddEntryPointFacades(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointFacadeFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
        
        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_a_static_target_containing_type_Should_not_generate_service_registration()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [ScopedEntryPointFacade]
                public partial interface IFacade;
                
                public static class TestEntryPoints
                {
                    [EntryPoint]
                    public static void Hello(string world) 
                    { 
                        Console.WriteLine($"hello {world}"); 
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world);
                    void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IFacade> _dispatcher;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }
            
                    public void Hello(string world)
                    {
                        Demo.TestEntryPoints.Hello(world);
                    }
            
                    public void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _dispatcher.Publish(context, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointFacadeFor_Demo_IFacade(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<ScopedDispatcher<Demo.IFacade>>();
                        services.AddTransient<IEntryPointRouter<Demo.IFacade>, DefaultEntryPointRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => Demo.TestEntryPoints.Hello(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context))));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPointFacade<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                        where T : EntryPointAttribute
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddEntryPointFacadeFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"No entry point discovery strategy found for type '{typeof(T).FullName}'");
                    }
            
                    public static IServiceCollection AddEntryPointFacades(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointFacadeFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
        
        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
   
    [Fact]
    public async Task Given_a_async_methods_Should_generate_async_entry_points_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [ScopedEntryPointFacade]
                public partial interface IFacade;
                
                public class TestEntryPoints
                {
                    [EntryPoint]
                    public Task Hello() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [EntryPoint]
                    public async Task<string> Hello(string world) 
                    { 
                        return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        
#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        const string expectedScopeCreation =
            "await using (var scope = _serviceProvider.CreateAsyncScope())";
#else
        const string expectedScopeCreation =
            "using (var scope = _serviceProvider.CreateScope())";
#endif
        
        const string expectedMainSource =
          $$"""
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    System.Threading.Tasks.Task Hello();
                    System.Threading.Tasks.Task<string> Hello(string world);
                    System.Threading.Tasks.Task PublishAsync(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task<T> SendAsync<T>(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IFacade> _dispatcher;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }
            
                    public async System.Threading.Tasks.Task Hello()
                    {
                        {{expectedScopeCreation}}
                        {
                            await scope.ServiceProvider.GetRequiredService<Demo.TestEntryPoints>().Hello().ConfigureAwait(false);
                        }
                    }
          
                    public async System.Threading.Tasks.Task<string> Hello(string world)
                    {
                        {{expectedScopeCreation}}
                        {
                            return await scope.ServiceProvider.GetRequiredService<Demo.TestEntryPoints>().Hello(world).ConfigureAwait(false);
                        }
                    }
            
                    public System.Threading.Tasks.Task PublishAsync(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.PublishAsync(context, cancellationToken);
                    }
            
                    public System.Threading.Tasks.Task<T> SendAsync<T>(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.SendAsync<T>(context, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointFacadeFor_Demo_IFacade(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<ScopedDispatcher<Demo.IFacade>>();
                        services.AddTransient<IEntryPointRouter<Demo.IFacade>, DefaultEntryPointRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello()));
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestEntryPoints>();
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPointFacade<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                        where T : EntryPointAttribute
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddEntryPointFacadeFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"No entry point discovery strategy found for type '{typeof(T).FullName}'");
                    }
            
                    public static IServiceCollection AddEntryPointFacades(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointFacadeFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_an_opt_out_from_generating_scopes_Should_not_generate_scopes()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [EntryPointFacade]
                public partial interface IFacade;
                
                public class TestEntryPoints
                {
                    [EntryPoint]
                    public void Hello() 
                    {
                    }
                    
                    [EntryPoint]
                    public string Hello(string world) 
                    { 
                        return world;
                    }
            
                    [EntryPoint]
                    public Task HelloAsync() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [EntryPoint]
                    public async Task<string> HelloAsync(string world) 
                    { 
                        return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        const string expectedMainSource =
          $$"""
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello();
                    string Hello(string world);
                    System.Threading.Tasks.Task HelloAsync();
                    System.Threading.Tasks.Task<string> HelloAsync(string world);
                    void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                    T Send<T>(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task PublishAsync(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task<T> SendAsync<T>(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IFacade> _dispatcher;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                        _dispatcher = dispatcher;
                    }
            
                    public void Hello()
                    {
                        _serviceProvider.GetRequiredService<Demo.TestEntryPoints>().Hello();
                    }
            
                    public string Hello(string world)
                    {
                        return _serviceProvider.GetRequiredService<Demo.TestEntryPoints>().Hello(world);
                    }
            
                    public async System.Threading.Tasks.Task HelloAsync()
                    {
                        await _serviceProvider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync().ConfigureAwait(false);
                    }
            
                    public async System.Threading.Tasks.Task<string> HelloAsync(string world)
                    {
                        return await _serviceProvider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync(world).ConfigureAwait(false);
                    }
            
                    public void Publish(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _dispatcher.Publish(context, cancellationToken);
                    }
            
                    public T Send<T>(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.Send<T>(context, cancellationToken);
                    }
            
                    public System.Threading.Tasks.Task PublishAsync(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.PublishAsync(context, cancellationToken);
                    }
            
                    public System.Threading.Tasks.Task<T> SendAsync<T>(Terminus.ParameterBindingContext context, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.SendAsync<T>(context, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddEntryPointFacadeFor_Demo_IFacade(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddSingleton(provider =>
                        {
                            var resolver = new ParameterBindingStrategyResolver(provider);
                            configure?.Invoke(resolver);
                            return resolver;
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IEntryPointRouter<Demo.IFacade>, DefaultEntryPointRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello()));
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context))));
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloAsync", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync()));
                        services.AddKeyedSingleton<EntryPointDescriptor<Terminus.EntryPointAttribute>>(typeof(Demo.IFacade), (provider, key) => new EntryPointDescriptor<Terminus.EntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloAsync", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync(provider.GetRequiredService<ParameterBindingStrategyResolver>().ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestEntryPoints>();
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPointFacade<T>(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                        where T : EntryPointAttribute
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddEntryPointFacadeFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"No entry point discovery strategy found for type '{typeof(T).FullName}'");
                    }
            
                    public static IServiceCollection AddEntryPointFacades(this IServiceCollection services, Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        services.AddEntryPointFacadeFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_the_entry_point_attribute_is_derived_Should_generate_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [EntryPointFacade(EntryPointAttributes = typeof(MyEntryPointAttribute))]
                public partial interface IFacade;
                
                public class MyEntryPointAttribute : EntryPointAttribute;
                
                public class TestEntryPoints
                {
                    [MyEntryPoint]
                    public void Hello() 
                    {
                    }
                    
                    [MyEntryPoint]
                    public string Hello(string world) 
                    { 
                        return world;
                    }
            
                    [MyEntryPoint]
                    public Task HelloAsync() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [MyEntryPoint]
                    public async Task<string> HelloAsync(string world) 
                    { 
                        return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        const string expectedMainSource =
          $$"""
            
            """;
        
        const string expectedServiceRegistrationSource =
            """
            
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator), 
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }
}
