using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class EntryPointDiscoveryGeneratorRouterTests
{
    [Fact]
    public async Task Given_the_presence_of_the_router_attribute_Should_generate_router_methods()
    {
        var asyncEnumerable = "";
        var expectedAsyncEnumerableRegistration = "";
#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        asyncEnumerable = 
            """
                [MyEntryPoint]
                public async IAsyncEnumerable<int> HelloStream()
                {
                    yield return 1;
                }
            """;
        expectedAsyncEnumerableRegistration =
            """
            services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IRouter), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloStream", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloStream()));
                        
            """;
#endif
        var source =
            $$"""
              using System;
              using System.Collections.Generic;
              using System.Threading.Tasks;
              using Terminus;

              namespace Demo
              {
                  [EntryPointRouter(EntryPointAttributes = [typeof(MyEntryPointAttribute)])]
                  public partial interface IRouter;

                  public class MyEntryPointAttribute : EntryPointAttribute;

                  public class TestEntryPoints
                  {
                      [MyEntryPoint]
                      public void Hello()
                      {
                      }

                      [MyEntryPoint]
                      public string Hello(string world)
                      {
                          return world;
                      }

                      [MyEntryPoint]
                      public Task HelloAsync()
                      {
                          return Task.CompletedTask;
                      }

                      [MyEntryPoint]
                      public async Task<string> HelloAsync(string world)
                      {
                           return await Task.FromResult(world);
                      }
                      
                      {{asyncEnumerable}}
                  }
              }
              """;

        var expectedMainSource =
            $$"""
              // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
              #nullable enable
              using Microsoft.Extensions.DependencyInjection;
              using System;
              using System.Reflection;
              using Terminus;
              using Terminus.Strategies;

              namespace Demo
              {
                  public partial interface IRouter
                  {
                      System.Threading.Tasks.Task<RouteResult> Route(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default);
                  }

                  internal sealed class IRouter_Generated : Demo.IRouter
                  {
                      private readonly IServiceProvider _serviceProvider;
                      private readonly Terminus.Dispatcher<Demo.IRouter> _dispatcher;
                      public IRouter_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IRouter> dispatcher)
                      {
                          _serviceProvider = serviceProvider;
                          _dispatcher = dispatcher;
                      }

                      public System.Threading.Tasks.Task<RouteResult> Route(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default)
                      {
                          cancellationToken.ThrowIfCancellationRequested();
                          return _dispatcher.Route(arguments, cancellationToken);
                      }
                  }
              }

              namespace Terminus
              {
                  public static partial class ServiceCollectionExtensions__Generated
                  {
                      private static IServiceCollection AddEntryPointsFor_Demo_IRouter(this IServiceCollection services, Action<ParameterBindingStrategyCollection>? configure = null)
                      {
                          services.AddKeyedSingleton<Terminus.ParameterBindingStrategyCollection>(typeof(Demo.IRouter), (provider, _) =>
                          {
                              var collection = new Terminus.ParameterBindingStrategyCollection();
                              configure?.Invoke(collection);
                              return collection;
                          });
                          services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IRouter), (provider, key) =>
                          {
                              var collection = provider.GetRequiredKeyedService<Terminus.ParameterBindingStrategyCollection>(key);
                              return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                          });
                          services.AddTransient<Dispatcher<Demo.IRouter>>();
                          services.AddTransient<IEntryPointRouter<Demo.IRouter>, DefaultEntryPointRouter<Demo.IRouter>>();
                          services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IRouter), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello()));
                          services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IRouter), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IRouter)).ResolveParameter<string>("world", context))));
                          services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IRouter), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloAsync", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync()));
                          services.AddKeyedSingleton<EntryPointDescriptor<Demo.MyEntryPointAttribute>>(typeof(Demo.IRouter), (provider, key) => new EntryPointDescriptor<Demo.MyEntryPointAttribute>(typeof(Demo.TestEntryPoints).GetMethod("HelloAsync", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestEntryPoints>().HelloAsync(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IRouter)).ResolveParameter<string>("world", context))));
                          {{expectedAsyncEnumerableRegistration}}services.AddTransient<Demo.TestEntryPoints>();
                          services.AddSingleton<Demo.IRouter, Demo.IRouter_Generated>();
                          return services;
                      }
                  }
              }
              """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPoints<T>(this IServiceCollection services, Action<ParameterBindingStrategyCollection>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IRouter":
                                return services.AddEntryPointsFor_Demo_IRouter(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }

                    public static IServiceCollection AddEntryPoints(this IServiceCollection services, Action<ParameterBindingStrategyCollection>? configure = null)
                    {
                        services.AddEntryPointsFor_Demo_IRouter();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<EntryPointDiscoveryGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "Demo_IRouter_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        test.TestState.GeneratedSources.Add((
            typeof(EntryPointDiscoveryGenerator),
            "__EntryPointServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));


        await test.RunAsync();
    }

}