using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class FacadeGeneratorAgnosticTests
{
    [Fact]
    public async Task Given_entry_point_methods_with_same_signature_but_in_different_types_When_one_set_of_methods_are_not_aggregate_Should_not_generate_duplicate_entry_point_diagnostic()
    {
        // An entry point not used in an aggregator (i.e. mediator or facade)
        // does not have an FacadeMethodDescriptor di registration generated
        const string source =
            """
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [ScopedFacadeOf(typeof(TestFacadeMethods))]
                public partial interface IFacade;

                public static class TestFacadeMethods
                {
                    [FacadeMethod]
                    public static void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"hello {world}");
                    }
                }

                public class MyService
                {
                    // duplicate signature in TestFacadeMethods should not create diagnostics because of
                    // the attribute constructor arg [ScopedFacadeOf(typeof(TestFacadeMethods))]
                    [FacadeMethod]
                    public void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"service hello {world}");
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;

            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, System.Threading.CancellationToken cancellationToken);
                }

                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    public void Hello(string world, System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        Demo.TestFacadeMethods.Hello(world, cancellationToken);
                    }
                }
            }

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string), typeof(System.Threading.CancellationToken) })!, (context, ct) => Demo.TestFacadeMethods.Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context), ct)));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }

                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
}
