using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class FacadeGeneratorTests
{
    [Fact]
    public async Task Given_a_single_parameter_method_Should_generate_entry_point_command()
    {
        const string source =
            """
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public static class TestFacadeMethods
                {
                    [FacadeMethod]
                    public static void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"hello {world}");
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, global::System.Threading.CancellationToken cancellationToken);
                }

                public sealed class IFacade_Generated : global::Demo.IFacade
                {
                    void global::Demo.IFacade.Hello(string world, global::System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        global::Demo.TestFacadeMethods.Hello(world, cancellationToken);
                    }
                }
            }
            """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        await test.RunAsync();
    }

    [Fact]
    public async Task Given_a_static_target_containing_type_Should_not_generate_service_registration()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute))]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public static class TestFacadeMethods
                {
                    [FacadeMethod]
                    public static void Hello(string world)
                    {
                        Console.WriteLine($"hello {world}");
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world);
                }

                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                public sealed class IFacade_Generated : global::Demo.IFacade
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IFacade.Hello(string world)
                    {
                        global::Demo.TestFacadeMethods.Hello(world);
                    }
                }
            }
            """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        await test.RunAsync();
    }

    [Fact]
    public async Task Given_a_async_methods_Should_generate_async_entry_points_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public Task HelloAsync()
                    {
                        return Task.CompletedTask;
                    }

                    [FacadeMethod]
                    public async Task<string> HelloAsync(string world)
                    {
                        return await Task.FromResult(world);
                    }

                    [FacadeMethod]
                    public void Hello()
                    {
                    }

                    [FacadeMethod]
                    public string Hello(string world)
                    {
                         return world;
                    }
                }
            }
            """;

        const string expectedMainSource =
            $$"""
              // <auto-generated/> Generated by Terminus FacadeGenerator
              #nullable enable
              namespace Demo
              {
                  public partial interface IFacade
                  {
                      global::System.Threading.Tasks.Task HelloAsync();
                      global::System.Threading.Tasks.Task<string> HelloAsync(string world);
                      void Hello();
                      string Hello(string world);
                  }

                  [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                  public sealed class IFacade_Generated : global::Demo.IFacade, global::System.IDisposable, global::System.IAsyncDisposable
                  {
                      private bool _syncDisposed;
                      private bool _asyncDisposed;
                      private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope> _syncScope;
                      private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope> _asyncScope;
                      public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                      {
                          _syncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>(serviceProvider).CreateScope());
                          _asyncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(serviceProvider));
                      }

                      async global::System.Threading.Tasks.Task global::Demo.IFacade.HelloAsync()
                      {
                          await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_asyncScope.Value.ServiceProvider).HelloAsync().ConfigureAwait(false);
                      }

                      async global::System.Threading.Tasks.Task<string> global::Demo.IFacade.HelloAsync(string world)
                      {
                          return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_asyncScope.Value.ServiceProvider).HelloAsync(world).ConfigureAwait(false);
                      }

                      void global::Demo.IFacade.Hello()
                      {
                          global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_syncScope.Value.ServiceProvider).Hello();
                      }

                      string global::Demo.IFacade.Hello(string world)
                      {
                          return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_syncScope.Value.ServiceProvider).Hello(world);
                      }

                      public void Dispose()
                      {
                          if (_syncDisposed || !_syncScope.IsValueCreated)
                              return;
                          _syncScope.Value.Dispose();
                          _syncDisposed = true;
                          global::System.GC.SuppressFinalize(this);
                      }

                      public async global::System.Threading.Tasks.ValueTask DisposeAsync()
                      {
                          if (_asyncDisposed || !_asyncScope.IsValueCreated)
                              return;
                          await _asyncScope.Value.DisposeAsync().ConfigureAwait(false);
                          _asyncDisposed = true;
                          global::System.GC.SuppressFinalize(this);
                      }
                  }
              }
              """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        await test.RunAsync();
    }

    [Fact]
    public async Task Given_an_opt_out_from_generating_scopes_Should_not_generate_scopes()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=false)]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public void Hello()
                    {
                    }

                    [FacadeMethod]
                    public string Hello(string world)
                    {
                       return world;
                    }

                    [FacadeMethod]
                    public Task HelloAsync()
                    {
                       return Task.CompletedTask;
                    }

                    [FacadeMethod]
                    public async Task<string> HelloAsync(string world)
                    {
                         return await Task.FromResult(world);
                    }
                }
            }
            """;

        const string expectedMainSource =
            $$"""
              // <auto-generated/> Generated by Terminus FacadeGenerator
              #nullable enable
              namespace Demo
              {
                  public partial interface IFacade
                  {
                      void Hello();
                      string Hello(string world);
                      global::System.Threading.Tasks.Task HelloAsync();
                      global::System.Threading.Tasks.Task<string> HelloAsync(string world);
                  }

                  [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                  public sealed class IFacade_Generated : global::Demo.IFacade
                  {
                      private readonly global::System.IServiceProvider _serviceProvider;
                      public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                      {
                          _serviceProvider = serviceProvider;
                      }

                      void global::Demo.IFacade.Hello()
                      {
                          global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_serviceProvider).Hello();
                      }

                      string global::Demo.IFacade.Hello(string world)
                      {
                          return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_serviceProvider).Hello(world);
                      }

                      async global::System.Threading.Tasks.Task global::Demo.IFacade.HelloAsync()
                      {
                          await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_serviceProvider).HelloAsync().ConfigureAwait(false);
                      }

                      async global::System.Threading.Tasks.Task<string> global::Demo.IFacade.HelloAsync(string world)
                      {
                          return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_serviceProvider).HelloAsync(world).ConfigureAwait(false);
                      }
                  }
              }
              """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        await test.RunAsync();
    }

    [Fact]
    public async Task Given_the_entry_point_attribute_is_derived_Should_generate_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(MyFacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;
                
                public class MyFacadeMethodAttribute : Attribute;
                
                public class TestFacadeMethods
                {
                    [MyFacadeMethod]
                    public void Hello() 
                    {
                    }
                    
                    [MyFacadeMethod]
                    public  string Hello(string world) 
                    { 
                        return world;
                    }

                    [MyFacadeMethod]
                    public Task HelloAsync() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [MyFacadeMethod]
                    public async Task<string> HelloAsync(string world) 
                    { 
                         return await Task.FromResult(world);
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello();
                    string Hello(string world);
                    global::System.Threading.Tasks.Task HelloAsync();
                    global::System.Threading.Tasks.Task<string> HelloAsync(string world);
                }

                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                public sealed class IFacade_Generated : global::Demo.IFacade, global::System.IDisposable, global::System.IAsyncDisposable
                {
                    private bool _syncDisposed;
                    private bool _asyncDisposed;
                    private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope> _syncScope;
                    private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope> _asyncScope;
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _syncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>(serviceProvider).CreateScope());
                        _asyncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(serviceProvider));
                    }

                    void global::Demo.IFacade.Hello()
                    {
                        global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_syncScope.Value.ServiceProvider).Hello();
                    }

                    string global::Demo.IFacade.Hello(string world)
                    {
                        return global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_syncScope.Value.ServiceProvider).Hello(world);
                    }

                    async global::System.Threading.Tasks.Task global::Demo.IFacade.HelloAsync()
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_asyncScope.Value.ServiceProvider).HelloAsync().ConfigureAwait(false);
                    }

                    async global::System.Threading.Tasks.Task<string> global::Demo.IFacade.HelloAsync(string world)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_asyncScope.Value.ServiceProvider).HelloAsync(world).ConfigureAwait(false);
                    }
            
                    public void Dispose()
                    {
                        if (_syncDisposed || !_syncScope.IsValueCreated)
                            return;
                        _syncScope.Value.Dispose();
                        _syncDisposed = true;
                        global::System.GC.SuppressFinalize(this);
                    }

                    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
                    {
                        if (_asyncDisposed || !_asyncScope.IsValueCreated)
                            return;
                        await _asyncScope.Value.DisposeAsync().ConfigureAwait(false);
                        _asyncDisposed = true;
                        global::System.GC.SuppressFinalize(this);
                    }
                }
            }
            """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        await test.RunAsync();
    }

#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
    [Fact]
    public async Task Given_IAsyncEnumerable_entry_point_in_scoped_facade_Should_create_async_method()
    {
        const string source =
            """
            using System.Collections.Generic;
            using Terminus;
            using System;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public async IAsyncEnumerable<int> Stream()
                    {
                        yield return 1;
                    }
                }
            }
            """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };
        string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                public partial interface IFacade
                {
                    global::System.Collections.Generic.IAsyncEnumerable<int> Stream();
                }

                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                public sealed class IFacade_Generated : global::Demo.IFacade, global::System.IDisposable, global::System.IAsyncDisposable
                {
                    private bool _syncDisposed;
                    private bool _asyncDisposed;
                    private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope> _syncScope;
                    private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope> _asyncScope;
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _syncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>(serviceProvider).CreateScope());
                        _asyncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(serviceProvider));
                    }

                    async global::System.Collections.Generic.IAsyncEnumerable<int> global::Demo.IFacade.Stream()
                    {
                        await foreach (var item in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.IFacade>(_asyncScope.Value.ServiceProvider).Stream())
                        {
                            yield return item;
                        }
                    }

                    public void Dispose()
                    {
                        if (_syncDisposed || !_syncScope.IsValueCreated)
                            return;
                        _syncScope.Value.Dispose();
                        _syncDisposed = true;
                        global::System.GC.SuppressFinalize(this);
                    }

                    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
                    {
                        if (_asyncDisposed || !_asyncScope.IsValueCreated)
                            return;
                        await _asyncScope.Value.DisposeAsync().ConfigureAwait(false);
                        _asyncDisposed = true;
                        global::System.GC.SuppressFinalize(this);
                    }
                }
            }
            """;

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator),
            "Demo_IFacade_Generated.g.cs",
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        await test.RunAsync();
    }
#endif
}
