using System.Text;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;

namespace Terminus.Generator.Tests.Unit.Generator;

public class FacadeGeneratorTests
{
    [Fact]
    public async Task Given_a_single_parameter_method_Should_generate_entry_point_command()
    {
        const string source =
            """
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;
            
                public class FacadeMethodAttribute : Attribute;
                
                public static class TestFacadeMethods
                {
                    [FacadeMethod]
                    public static void Hello(string world, CancellationToken cancellationToken) 
                    { 
                        Console.WriteLine($"hello {world}"); 
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, System.Threading.CancellationToken cancellationToken);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Hello(string world, System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        Demo.TestFacadeMethods.Hello(world, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string), typeof(System.Threading.CancellationToken) })!, (context, ct) => Demo.TestFacadeMethods.Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context), ct)));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
        
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_a_static_target_containing_type_Should_not_generate_service_registration()
    {
        const string source =
            """
            using System;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;
            
                public class FacadeMethodAttribute : Attribute;
                
                public static class TestFacadeMethods
                {
                    [FacadeMethod]
                    public static void Hello(string world) 
                    { 
                        Console.WriteLine($"hello {world}"); 
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Hello(string world)
                    {
                        Demo.TestFacadeMethods.Hello(world);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => Demo.TestFacadeMethods.Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context))));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
        
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
   
    [Fact]
    public async Task Given_a_async_methods_Should_generate_async_entry_points_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;
            
                public class FacadeMethodAttribute : Attribute;
                
                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public Task Hello() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [FacadeMethod]
                    public async Task<string> Hello(string world) 
                    { 
                         return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        
#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
        const string expectedScopeCreation =
            "await using (var scope = _serviceProvider.CreateAsyncScope())";
#else
        const string expectedScopeCreation =
            "using (var scope = _serviceProvider.CreateScope())";
#endif
        
        const string expectedMainSource =
          $$"""
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    System.Threading.Tasks.Task Hello();
                    System.Threading.Tasks.Task<string> Hello(string world);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public async System.Threading.Tasks.Task Hello()
                    {
                        {{expectedScopeCreation}}
                        {
                            await scope.ServiceProvider.GetRequiredService<Demo.TestFacadeMethods>().Hello().ConfigureAwait(false);
                        }
                    }
          
                    public async System.Threading.Tasks.Task<string> Hello(string world)
                    {
                        {{expectedScopeCreation}}
                        {
                            return await scope.ServiceProvider.GetRequiredService<Demo.TestFacadeMethods>().Hello(world).ConfigureAwait(false);
                        }
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestFacadeMethods>();
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_an_opt_out_from_generating_scopes_Should_not_generate_scopes()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf]
                public partial interface IFacade;
                
                public FacadeOfAttribute : Attribute;
                
                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public void Hello() 
                    {
                    }
                    
                    [FacadeMethod]
                    public string Hello(string world) 
                    { 
                        return world;
                    }
            
                    [FacadeMethod]
                    public Task HelloAsync() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [FacadeMethod]
                    public async Task<string> HelloAsync(string world) 
                    { 
                         return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        const string expectedMainSource =
          $$"""
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello();
                    string Hello(string world);
                    System.Threading.Tasks.Task HelloAsync();
                    System.Threading.Tasks.Task<string> HelloAsync(string world);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Hello()
                    {
                        _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().Hello();
                    }
            
                    public string Hello(string world)
                    {
                        return _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().Hello(world);
                    }
            
                    public async System.Threading.Tasks.Task HelloAsync()
                    {
                        await _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync().ConfigureAwait(false);
                    }
            
                    public async System.Threading.Tasks.Task<string> HelloAsync(string world)
                    {
                        return await _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync(world).ConfigureAwait(false);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context))));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("HelloAsync", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("HelloAsync", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestFacadeMethods>();
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_the_entry_point_attribute_is_derived_Should_generate_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(FacadeMethodAttributes = [typeof(MyFacadeMethodAttribute)])]
                public partial interface IFacade;
                
                public class MyFacadeMethodAttribute : FacadeMethodAttribute;
                
                public class TestFacadeMethods
                {
                    [MyFacadeMethod]
                    public void Hello() 
                    {
                    }
                    
                    [MyFacadeMethod]
                    public  string Hello(string world) 
                    { 
                        return world;
                    }
            
                    [MyFacadeMethod]
                    public Task HelloAsync() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [MyFacadeMethod]
                    public async Task<string> HelloAsync(string world) 
                    { 
                         return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello();
                    string Hello(string world);
                    System.Threading.Tasks.Task HelloAsync();
                    System.Threading.Tasks.Task<string> HelloAsync(string world);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Hello()
                    {
                        _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().Hello();
                    }
            
                    public string Hello(string world)
                    {
                        return _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().Hello(world);
                    }
            
                    public async System.Threading.Tasks.Task HelloAsync()
                    {
                        await _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync().ConfigureAwait(false);
                    }
            
                    public async System.Threading.Tasks.Task<string> HelloAsync(string world)
                    {
                        return await _serviceProvider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync(world).ConfigureAwait(false);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context))));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("HelloAsync", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("HelloAsync", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestFacadeMethods>();
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_the_presence_of_the_mediator_attribute_Should_not_generate_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeMethodMediator(FacadeMethodAttributes = [typeof(MyFacadeMethodAttribute)])]
                public partial interface IMediator;
                
                public class MyFacadeMethodAttribute : FacadeMethodAttribute;
                
                public class TestFacadeMethods
                {
                    [MyFacadeMethod]
                    public void Hello() 
                    {
                    }
                    
                    [MyFacadeMethod]
                    public  string Hello(string world) 
                    { 
                        return world;
                    }
            
                    [MyFacadeMethod]
                    public Task HelloAsync() 
                    { 
                        return Task.CompletedTask;
                    }
                    
                    [MyFacadeMethod]
                    public async Task<string> HelloAsync(string world) 
                    { 
                         return await Task.FromResult(world);
                    }
                }
            }
            """;
        
        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IMediator
                {
                    void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default);
                    T Send<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task PublishAsync(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default);
                    System.Threading.Tasks.Task<T> SendAsync<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IMediator_Generated : Demo.IMediator
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IMediator> _dispatcher;
                    public IMediator_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IMediator> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        _dispatcher.Publish(arguments, cancellationToken);
                    }
            
                    public T Send<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.Send<T>(arguments, cancellationToken);
                    }
            
                    public System.Threading.Tasks.Task PublishAsync(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.PublishAsync(arguments, cancellationToken);
                    }
            
                    public System.Threading.Tasks.Task<T> SendAsync<T>(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        return _dispatcher.SendAsync<T>(arguments, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IMediator(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IMediator), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IMediator), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IMediator>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IMediator>, DefaultFacadeMethodRouter<Demo.IMediator>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IMediator), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IMediator), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IMediator)).ResolveParameter<string>("world", context))));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IMediator), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("HelloAsync", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync()));
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>>(typeof(Demo.IMediator), (provider, key) => new FacadeMethodDescriptor<Demo.MyFacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("HelloAsync", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().HelloAsync(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IMediator)).ResolveParameter<string>("world", context))));
                        services.AddTransient<Demo.TestFacadeMethods>();
                        services.AddSingleton<Demo.IMediator, Demo.IMediator_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IMediator":
                                return services.AddFacadeMethodsFor_Demo_IMediator(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IMediator();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IMediator_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
       
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));
        

        await test.RunAsync();
    }

#if NETCOREAPP3_0_OR_GREATER || NETSTANDARD2_1_OR_GREATER
    [Fact]
    public async Task Given_IAsyncEnumerable_entry_point_in_scoped_facade_Should_create_async_method()
    {
        const string source =
            """
            using System.Collections.Generic;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;
            
                public class FacadeMethodAttribute : Attribute;

                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public async IAsyncEnumerable<int> Stream()
                    {
                        yield return 1;
                    }
                }
            }
            """;

        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };
        string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    System.Collections.Generic.IAsyncEnumerable<int> Stream();
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public async System.Collections.Generic.IAsyncEnumerable<int> Stream()
                    {
                        await using (var scope = _serviceProvider.CreateAsyncScope())
                        {
                            await foreach (var item in scope.ServiceProvider.GetRequiredService<IFacade>().Stream())
                            {
                                yield return item;
                            }
                        }
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Stream", new System.Type[] { })!, (context, ct) => provider.GetRequiredService<Demo.TestFacadeMethods>().Stream()));
                        services.AddTransient<Demo.TestFacadeMethods>();
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;
        
        string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;
        
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
        
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
#endif

    [Fact]
    public async Task Given_ScopedFacadeMethodMediator_with_custom_attribute_Should_generate_AddFacadeMethods_not_AddFacadeMethodMediator()
    {
        const string source =
            """
            using System;
            using Microsoft.Extensions.DependencyInjection;
            using Terminus;

            namespace Demo
            {
                [ScopedFacadeMethodMediator(FacadeMethodAttributes = [typeof(MyCustomAttribute)])]
                public partial interface IDispatcher;

                [AttributeUsage(AttributeTargets.Method)]
                public class MyCustomAttribute(string path) : FacadeMethodAttribute
                {
                    public string Path { get; } = path;
                }

                public class MyController
                {
                    [MyCustomAttribute("/users/{id}")]
                    public void GetUser(string id) { }
                }

                public class Program
                {
                    public static void Main()
                    {
                        var services = new ServiceCollection();

                        // This should fail because the generated method is AddFacadeMethods, not AddFacadeMethodMediator
                        services.AddFacadeMethods<IDispatcher>();
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IDispatcher
                {
                    void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default);
                }
            
                internal sealed class IDispatcher_Generated : Demo.IDispatcher
                {
                    private readonly IServiceProvider _serviceProvider;
                    private readonly Terminus.Dispatcher<Demo.IDispatcher> _dispatcher;
                    public IDispatcher_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IDispatcher> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Publish(System.Collections.Generic.IReadOnlyDictionary<string, object?> arguments, System.Threading.CancellationToken cancellationToken = default)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        using (var scope = _serviceProvider.CreateScope())
                        {
                            _dispatcher.Publish(arguments, cancellationToken);
                        }
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IDispatcher(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IDispatcher), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IDispatcher), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IDispatcher>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IDispatcher>, DefaultFacadeMethodRouter<Demo.IDispatcher>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Demo.MyCustomAttribute>>(typeof(Demo.IDispatcher), (provider, key) => new FacadeMethodDescriptor<Demo.MyCustomAttribute>(typeof(Demo.MyController).GetMethod("GetUser", new System.Type[] { typeof(string) })!, (context, ct) => provider.GetRequiredService<Demo.MyController>().GetUser(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IDispatcher)).ResolveParameter<string>("id", context))));
                        services.AddTransient<Demo.MyController>();
                        services.AddSingleton<Demo.IDispatcher, Demo.IDispatcher_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IDispatcher":
                                return services.AddFacadeMethodsFor_Demo_IDispatcher(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IDispatcher();
                        return services;
                    }
                }
            }
            """;
        
        var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IDispatcher_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();

        await test.RunAsync();
    }
    
    [Fact]
    public async Task Given_entry_point_methods_with_same_signature_but_in_different_types_When_one_set_of_methods_are_not_aggregate_Should_not_generate_duplicate_entry_point_diagnostic()
    {
        // An entry point not used in an aggregator (i.e. mediator or facade)
        // does not have an FacadeMethodDescriptor di registration generated
        const string source =
            """
            using System;
            using Terminus;
            using System.Threading;

            namespace Demo
            {
                [ScopedFacadeOf(typeof(TestFacadeMethods))]
                public partial interface IFacade;

                public static class TestFacadeMethods
                {
                    [FacadeMethod]
                    public static void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"hello {world}");
                    }
                }

                public class MyService
                {
                    // duplicate signature in TestFacadeMethods should not create diagnostics because of 
                    // the attribute constructor arg [ScopedFacadeOf(typeof(TestFacadeMethods))]
                    [FacadeMethod]
                    public void Hello(string world, CancellationToken cancellationToken)
                    {
                        Console.WriteLine($"service hello {world}");
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;
            
            namespace Demo
            {
                public partial interface IFacade
                {
                    void Hello(string world, System.Threading.CancellationToken cancellationToken);
                }
            
                internal sealed class IFacade_Generated : Demo.IFacade
                {
                    private readonly IServiceProvider _serviceProvider;
                    public IFacade_Generated(IServiceProvider serviceProvider, Terminus.Dispatcher<Demo.IFacade> dispatcher)
                    {
                        _serviceProvider = serviceProvider;
                    }
            
                    public void Hello(string world, System.Threading.CancellationToken cancellationToken)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                        Demo.TestFacadeMethods.Hello(world, cancellationToken);
                    }
                }
            }
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    private static IServiceCollection AddFacadeMethodsFor_Demo_IFacade(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddKeyedSingleton<Terminus.FacadeMethodOptions>(typeof(Demo.IFacade), (provider, _) =>
                        {
                            var collection = new Terminus.FacadeMethodOptions();
                            configure?.Invoke(collection);
                            return collection;
                        });
                        services.AddKeyedTransient<Terminus.ParameterBindingStrategyResolver>(typeof(Demo.IFacade), (provider, key) =>
                        {
                            var collection = provider.GetRequiredKeyedService<Terminus.FacadeMethodOptions>(key);
                            return new Terminus.ParameterBindingStrategyResolver(provider, collection);
                        });
                        services.AddTransient<Dispatcher<Demo.IFacade>>();
                        services.AddTransient<IFacadeMethodRouter<Demo.IFacade>, DefaultFacadeMethodRouter<Demo.IFacade>>();
                        services.AddKeyedSingleton<FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>>(typeof(Demo.IFacade), (provider, key) => new FacadeMethodDescriptor<Terminus.FacadeMethodAttribute>(typeof(Demo.TestFacadeMethods).GetMethod("Hello", new System.Type[] { typeof(string), typeof(System.Threading.CancellationToken) })!, (context, ct) => Demo.TestFacadeMethods.Hello(provider.GetRequiredKeyedService<ParameterBindingStrategyResolver>(typeof(Demo.IFacade)).ResolveParameter<string>("world", context), ct)));
                        services.AddSingleton<Demo.IFacade, Demo.IFacade_Generated>();
                        return services;
                    }
                }
            }
            """;

        const string expectedServiceRegistrationSource =
            """
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            
            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddFacadeMethods<T>(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        switch (typeof(T).FullName)
                        {
                            case "Demo.IFacade":
                                return services.AddFacadeMethodsFor_Demo_IFacade(configure);
                        };
                        throw new InvalidOperationException($"The type '{typeof(T).FullName}' is not an entry point aggregator");
                    }
            
                    public static IServiceCollection AddFacadeMethods(this IServiceCollection services, Action<FacadeMethodOptions>? configure = null)
                    {
                        services.AddFacadeMethodsFor_Demo_IFacade();
                        return services;
                    }
                }
            }
            """;

    var test = new TerminusSourceGeneratorTest<FacadeGenerator>
        {
            TestState =
            {
                Sources = { source }
            }
        };

        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "Demo_IFacade_Generated.g.cs", 
            SourceText.From(expectedMainSource, Encoding.UTF8)));
        
        test.TestState.GeneratedSources.Add((
            typeof(FacadeGenerator), 
            "__FacadeMethodServiceRegistration_Generated.g.cs",
            SourceText.From(expectedServiceRegistrationSource, Encoding.UTF8)));

        await test.RunAsync();
    }
}
