using System.Text;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;
using Xunit;

namespace Terminus.Generator.Tests.Unit.Generator;

public class OpenGenericCrossAssemblyTests
{
    [Fact]
    public async Task Given_OpenGenericInReferencedAssembly_With_MethodDiscovery_ReferencedAssemblies_Should_Discover_Implementations()
    {
        // Arrange: Source code for the referenced assembly
        const string referencedAssemblySource = """
            using System;
            using Terminus;

            namespace ExternalLib
            {
                public class HandlerAttribute : Attribute { }

                [Handler]
                public interface IHandler<T>
                {
                    void Handle(T value);
                }

                public class StringHandler : IHandler<string>
                {
                    public void Handle(string value) => Console.WriteLine(value);
                }
            }
            """;

        // Arrange: Source code for the main project
        const string mainSource = """
            using System;
            using Terminus;
            using ExternalLib;

            namespace Demo
            {
                [FacadeOf(typeof(HandlerAttribute), MethodDiscovery = MethodDiscoveryMode.ReferencedAssemblies)]
                public partial interface IHandlers;
            }
            """;

        // Act & Assert
        var test = new TerminusSourceGeneratorTest<FacadeGenerator>();
        await test.AddReferencedAssemblyFromSourceAsync(referencedAssemblySource, "ExternalLib");
        test.TestState.Sources.Add(mainSource);
        
        const string expectedOutput = """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="ExternalLib.IHandler<string>"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IHandlers
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="ExternalLib.IHandler<string>.Handle(string)"/>
                    /// </summary>
                    void Handle(string value);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IHandlers))]
                /// <summary>
                /// Facade implementation class delegating to: <see cref="ExternalLib.IHandler<string>"/>
                /// </summary>
                public sealed class IHandlers_Generated : global::Demo.IHandlers
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    /// <summary>
                    /// Initializes a new instance of the IHandlers_Generated class.
                    /// </summary>
                    /// <param name = "serviceProvider">The service provider used for resolving dependencies.</param>
                    public IHandlers_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    void global::Demo.IHandlers.Handle(string value)
                    {
                        foreach (var handler in global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<global::ExternalLib.IHandler<string>>(_serviceProvider))
                        {
                            handler.Handle(value);
                        }
                    }
                }
            }
            """;

        test.TestState.GeneratedSources.Add(
            (typeof(FacadeGenerator), "Demo_IHandlers_Generated.g.cs",
             SourceText.From(NormalizeLineEndings(expectedOutput), Encoding.UTF8)));

        await test.RunAsync();
    }
    
    private static string NormalizeLineEndings(string text) => text.Replace("\r\n", "\n").Replace("\n", Environment.NewLine);
}
