using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Terminus.Generator.Tests.Unit.Generator.Infrastructure;
using Xunit;

namespace Terminus.Generator.Tests.Unit.Generator;

public class ValueTaskSupportTests : SourceGeneratorTestBase<FacadeGenerator>
{
    [Fact]
    public async Task Given_ValueTask_methods_Should_generate_async_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), Scoped=true)]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public ValueTask HelloAsync()
                    {
                        return default;
                    }

                    [FacadeMethod]
                    public async ValueTask<string> HelloAsync(string world)
                    {
                        return world;
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.TestFacadeMethods"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IFacade
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestFacadeMethods.HelloAsync"/>
                    /// </summary>
                    global::System.Threading.Tasks.ValueTask HelloAsync();
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestFacadeMethods.HelloAsync(string)"/>
                    /// </summary>
                    global::System.Threading.Tasks.ValueTask<string> HelloAsync(string world);
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                public sealed class IFacade_Generated : global::Demo.IFacade, global::System.IDisposable, global::System.IAsyncDisposable
                {
                    private bool _syncDisposed;
                    private bool _asyncDisposed;
                    private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope> _syncScope;
                    private readonly global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope> _asyncScope;
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _syncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.IServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Microsoft.Extensions.DependencyInjection.IServiceScopeFactory>(serviceProvider).CreateScope());
                        _asyncScope = new global::System.Lazy<global::Microsoft.Extensions.DependencyInjection.AsyncServiceScope>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(serviceProvider));
                    }

                    async global::System.Threading.Tasks.ValueTask global::Demo.IFacade.HelloAsync()
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_asyncScope.Value.ServiceProvider).HelloAsync().ConfigureAwait(false);
                    }

                    async global::System.Threading.Tasks.ValueTask<string> global::Demo.IFacade.HelloAsync(string world)
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_asyncScope.Value.ServiceProvider).HelloAsync(world).ConfigureAwait(false);
                    }

                    public void Dispose()
                    {
                        if (_syncDisposed || !_syncScope.IsValueCreated)
                            return;
                        _syncScope.Value.Dispose();
                        _syncDisposed = true;
                        global::System.GC.SuppressFinalize(this);
                    }

                    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
                    {
                        if (_asyncDisposed || !_asyncScope.IsValueCreated)
                            return;
                        await _asyncScope.Value.DisposeAsync().ConfigureAwait(false);
                        _asyncDisposed = true;
                        global::System.GC.SuppressFinalize(this);
                    }
                }
            }
            """;

        await VerifyAsync(
            source,
            ("Demo_IFacade_Generated.g.cs", expectedMainSource));
    }

    [Fact]
    public async Task Given_ValueTask_methods_with_custom_names_Should_generate_renamed_async_facade_methods()
    {
        const string source =
            """
            using System;
            using System.Threading.Tasks;
            using Terminus;

            namespace Demo
            {
                [FacadeOf(typeof(FacadeMethodAttribute), AsyncCommandName="DoAsync", AsyncQueryName="GetAsync")]
                public partial interface IFacade;

                public class FacadeMethodAttribute : Attribute;

                public class TestFacadeMethods
                {
                    [FacadeMethod]
                    public ValueTask HelloCommandAsync()
                    {
                        return default;
                    }

                    [FacadeMethod]
                    public async ValueTask<string> HelloQueryAsync()
                    {
                        return "world";
                    }
                }
            }
            """;

        const string expectedMainSource =
            """
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            namespace Demo
            {
                /// <summary>
                /// Facade interface delegating to: <see cref="Demo.TestFacadeMethods"/>
                /// </summary>
                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                public partial interface IFacade
                {
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestFacadeMethods.HelloCommandAsync"/>
                    /// </summary>
                    global::System.Threading.Tasks.ValueTask DoAsync();
                    /// <summary>
                    /// Delegates to:<br/>
                    /// <see cref="Demo.TestFacadeMethods.HelloQueryAsync"/>
                    /// </summary>
                    global::System.Threading.Tasks.ValueTask<string> GetAsync();
                }

                [global::System.CodeDom.Compiler.GeneratedCode("Terminus.Generator", "1.0.0")]
                [global::Terminus.FacadeImplementation(typeof(global::Demo.IFacade))]
                public sealed class IFacade_Generated : global::Demo.IFacade
                {
                    private readonly global::System.IServiceProvider _serviceProvider;
                    public IFacade_Generated(global::System.IServiceProvider serviceProvider)
                    {
                        _serviceProvider = serviceProvider;
                    }

                    async global::System.Threading.Tasks.ValueTask global::Demo.IFacade.DoAsync()
                    {
                        await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_serviceProvider).HelloCommandAsync().ConfigureAwait(false);
                    }

                    async global::System.Threading.Tasks.ValueTask<string> global::Demo.IFacade.GetAsync()
                    {
                        return await global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Demo.TestFacadeMethods>(_serviceProvider).HelloQueryAsync().ConfigureAwait(false);
                    }
                }
            }
            """;

        await VerifyAsync(
            source,
            ("Demo_IFacade_Generated.g.cs", expectedMainSource));
    }
}
