using Microsoft.CodeAnalysis.CSharp.Syntax;
using Terminus.Generator.Builders.Namespace;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Terminus.Generator.Builders;

/// <summary>
/// Top-level orchestrator for generating complete facade source files.
/// Replaces the old SourceBuilder.
/// </summary>
internal static class FacadeBuilderOrchestrator
{
    /// <summary>
    /// Generates the complete compilation unit for a facade.
    /// </summary>
    public static CompilationUnitSyntax Generate(FacadeGenerationContext context)
    {
        var namespaceDeclaration = NamespaceBuilder.Build(
            context.Facade,
            context.FacadeMethodMethodInfos);

        var namespaceCode = namespaceDeclaration.ToFullString().TrimStart();

        var rawCompilationUnit =
          $$"""
            // <auto-generated/> Generated by Terminus FacadeGenerator
            #nullable enable
            {{namespaceCode}}
            """;

        return ParseCompilationUnit(rawCompilationUnit);
    }
}
