using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Terminus.Generator.Builders.Namespace;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace Terminus.Generator.Builders;

/// <summary>
/// Top-level orchestrator for generating complete facade source files.
/// Replaces the old SourceBuilder.
/// </summary>
internal static class FacadeBuilderOrchestrator
{
    /// <summary>
    /// Generates the complete compilation unit for a facade.
    /// </summary>
    public static CompilationUnitSyntax Generate(FacadeGenerationContext context)
    {
        var members = NamespaceBuilder.Build(
            context.Facade,
            context.FacadeMethodMethodInfos);

        return CompilationUnit()
            .WithMembers(List(members))
            .WithLeadingTrivia(
                Comment("// <auto-generated/> Generated by Terminus FacadeGenerator"),
                Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)))
            .NormalizeWhitespace();
    }
}
