using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static Terminus.Generator.Builders.MediatorBuilder;
using static Terminus.Generator.Builders.ServiceRegistrationBuilder;

namespace Terminus.Generator.Builders;

internal static class SourceBuilder
{
    internal static CompilationUnitSyntax GenerateEntryPoints(EntryPointsContext entryPointsContext)
    {
        var entryPointAttributeType = entryPointsContext.EntryPointAttributeType;
        var entryPointMethodInfos = entryPointsContext.EntryPointMethodInfos;
        var mediators = entryPointsContext.Mediators;

        var rawCompilationUnit =
          $$"""
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;

            {{GenerateMediatorTypeDeclarations(entryPointMethodInfos, mediators)}}

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    {{CreateAddEntryPointsMethods(entryPointAttributeType, mediators, entryPointMethodInfos)}}
                }
            }
            """;

        return ParseCompilationUnit(rawCompilationUnit).NormalizeWhitespace();
    }

    internal static CompilationUnitSyntax GenerateServiceRegistrations(ImmutableArray<INamedTypeSymbol> entryPointAttributeTypes)
    {
        var compilationUnit =
          $$"""
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;

            namespace Terminus
            {
                public static partial class ServiceCollectionExtensions__Generated
                {
                    public static IServiceCollection AddEntryPoints<T>(
                        this IServiceCollection services,
                        Action<ParameterBindingStrategyResolver>? configure = null) where T : EntryPointAttribute
                    {
                        {{GenerateRegistrationMethodSelector(entryPointAttributeTypes)}};
                                  
                        throw new InvalidOperationException($"No entry point discovery strategy found for type '{typeof(T).FullName}'");   
                    }
                              
                    public static IServiceCollection AddEntryPoints(
                        this IServiceCollection services,
                        Action<ParameterBindingStrategyResolver>? configure = null)
                    {
                        {{GenerateRegistrationsPerAttribute(entryPointAttributeTypes)}}
                                  
                        return services;
                    }
                }
            }
            """;
        
        return ParseCompilationUnit(compilationUnit).NormalizeWhitespace();
    }
}