using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
using static Terminus.Generator.Builders.AggregatorBuilder;

namespace Terminus.Generator.Builders;

internal static class SourceBuilder
{
    internal static CompilationUnitSyntax GenerateAggregatorEntryPoints(AggregatorContext aggregatorContext)
    {

        var rawCompilationUnit =
          $$"""
            // <auto-generated/> Generated by Terminus EntryPointDiscoveryGenerator
            #nullable enable
            using Microsoft.Extensions.DependencyInjection;
            using System;
            using System.Reflection;
            using Terminus;
            using Terminus.Strategies;

            {{GenerateAggregatorTypeDeclarations(aggregatorContext)}}
            """;

        return ParseCompilationUnit(rawCompilationUnit).NormalizeWhitespace();
    }
}